import { join } from 'node:path';
import { test, expect, enterClassroom, typeInput, sendInput, openRoot, openAppearance, closeAppearance } from './fixtures/classroom.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { CourseView } from '@studyforge/contracts/courses';
import type { SessionListValue } from '@deepseek-ai/dsh-api-session-controller';

test('learning modes stay inside the native composer and real recommendations hide only after acceptance', async ({ page, classroom }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1280, height: 900 });
  await enterClassroom(page, classroom.authUrl);
  const input = page.locator('[data-composer-input]'), mode = page.getByTestId('agent-role');
  await expect(input).toHaveAttribute('aria-label', '写下你想学习的内容…');
  await expect(mode).toBeVisible(); await expect(mode).toHaveAttribute('value', 'teacher');
  await expect(page.getByTestId('learning-entry')).toHaveCount(0);
  await expect(page.getByRole('button', { name: /Access mode|工作区内修改/ })).toHaveCount(0);
  await expect(page.locator('[data-composer-seat] [class*="_tools"] button[class*="_add"]:visible')).toHaveCount(0);
  await expect(page.getByTestId('notebook-sidebar').locator('.sf-notebook-controls')).toHaveCount(0);
  const client = await connectRuntime(classroom);
  const created = await client.rpc<{ sessionId: string }>('session/create', { request: { cwd: join(classroom.root, 'classroom'), agentPreset: 'studyforge-learning' } });
  if (!created.ok) throw new Error('fixture session failed');
  const id = created.value.sessionId;
  await client.rpc('session/prompt', { request: { sessionId: id, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '继续检查三角函数基础' }] } });
  const course = await client.rpc<CourseView>('studyforgeCourses/read', { input: { sessionId: id } });
  if (!course.ok) throw new Error('fixture course missing');
  const updated = await client.rpc('studyforgeCourses/update', { input: { sessionId: id, operationId: 'guided-fixture', expectedVersion: course.value.version, patch: { guided: true, teachingRef: 'diagnose', learningGoal: { title: '三角函数基础' } } } });
  if (!updated.ok) throw new Error('fixture goal failed');
  await page.reload();
  await expect(page.getByTestId('learning-entry')).toContainText('三角函数基础');
  await typeInput(page, '我想学习三角函数');
  await expect(mode).toHaveAttribute('value', 'teacher');
  await expect(input).toContainText('我想学习三角函数');
  const b = (await input.boundingBox())!, m = (await mode.boundingBox())!;
  expect(m.y).toBeGreaterThan(b.y); expect(m.y - b.y).toBeLessThan(120);
  const a = (await page.getByTestId('learning-entry').boundingBox())!;
  expect(a.y).toBeGreaterThan(m.y + m.height);
  await page.screenshot({ path: info.outputPath('home-modes-and-suggestions.png'), fullPage: true });
  await page.getByRole('button', { name: '更多学习操作', exact: true }).click();
  await expect(page.getByRole('button', { name: '打开资料库', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '整理成讲义', exact: true }).click();
  await expect(input).toContainText('我想学习三角函数');
  await expect(page.locator('[data-composer-chip="studyforge-task"]')).toContainText('整理成讲义');
  await expect(page.getByTestId('learning-entry')).toBeVisible();
  await page.locator('[data-composer-seat] input[type="file"][hidden]').setInputFiles({ name: '临时说明.txt', mimeType: 'text/plain', buffer: Buffer.from('一份仅用于当前对话的附件') });
  await expect(page.getByText('临时说明.txt', { exact: false }).first()).toBeVisible();
  await page.getByRole('button', { name: '更多学习操作', exact: true }).click();
  await page.getByRole('button', { name: '检查我的理解', exact: true }).click();
  await expect(input).toContainText('检查我对当前内容的理解');
  await expect(page.getByText('临时说明.txt', { exact: false }).first()).toBeVisible();
  const model = page.locator('[data-slot="conversation.input.model"] button').first();
  await expect(model).toBeVisible();
  const modelBox = (await model.boundingBox())!;
  const modeBox = (await mode.boundingBox())!;
  expect(modelBox.x).toBeGreaterThan(modeBox.x);
  expect(Math.abs(modelBox.y - modeBox.y)).toBeLessThan(12);
  expect(modelBox.x - modeBox.x - modeBox.width).toBeLessThan(180);
  expect(await mode.evaluate(el => getComputedStyle(el).fontFamily)).not.toMatch(/hand|Kaiti|KaiTi|手写/i);
  expect(await mode.evaluate(el => getComputedStyle(el).fontFamily)).toBe(await model.evaluate(el => getComputedStyle(el).fontFamily));
  let rejectFirst = true;
  await page.route('**/api/session/prompt', async route => {
    if (!rejectFirst) { await route.continue(); return; }
    rejectFirst = false;
    const request = route.request().postDataJSON() as { rpcId: string };
    await route.fulfill({ json: { type: 'server-response', rpcId: request.rpcId, result: { ok: false, error: { code: 'gateway/internal', message: 'Fixture admission rejected', details: {} } } } });
  });
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(input).toContainText('我想学习三角函数'); await expect(page.getByTestId('learning-entry')).toBeVisible();
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByTestId('learning-entry')).toHaveCount(0); await expect(mode).toBeVisible();
  await openRoot(page, '首页');
  await openAppearance(page); await page.getByTestId('theme-notebook').click(); await page.getByTestId('notebook-tone').selectOption('white'); await closeAppearance(page);
  await page.setViewportSize({ width: 500, height: 800 });
  await expect(mode).toBeVisible();
  await page.screenshot({ path: info.outputPath('home-modes-narrow.png'), fullPage: true });
  await expect.poll(() => page.locator('[data-composer-seat]').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});

test('blank classroom offers a guided planning entry that stages the first message', async ({ page, classroom }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await enterClassroom(page, classroom.authUrl);
  const input = page.locator('[data-composer-input]');
  await page.getByRole('button', { name: '更多学习操作', exact: true }).click();
  const plan = page.getByTestId('learning-entry-plan');
  await expect(plan).toBeVisible();
  await plan.click();
  await expect(input).toContainText('我想规划一下自己的学习');
  const client = await connectRuntime(classroom);
  const listed = await client.rpc<SessionListValue>('session/list', { _request: {} });
  if (!listed.ok) throw new Error('session list failed');
  const session = listed.value.items.find(item => item.origin !== 'subagent');
  if (!session) throw new Error('classroom session missing');
  const course = await client.rpc<CourseView>('studyforgeCourses/read', { input: { sessionId: session.sessionId } });
  if (!course.ok) throw new Error('course read failed');
  expect(course.value.data.guided).toBe(true);
  expect(course.value.data.teachingRef).toBe('diagnose');
  await sendInput(page, '我想规划一下自己的学习。');
  await expect(page.getByTestId('learning-entry')).toHaveCount(0);
  expect(errors).toEqual([]);
});
