import { test, expect, enterClassroom, openCoursesList, openRoot, openAppearance, closeAppearance, sendInput, openCourseDetail } from './fixtures/classroom.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { RouteView } from '@studyforge/contracts/routes';
import type { CardView } from '@studyforge/contracts/cards';
import type { ProposalView } from '@studyforge/contracts/proposals';
import type { CalendarDay } from '@studyforge/contracts/calendar';
import { civilDayIn } from '../../packages/client/src/courses/format.ts';
const value = <T,>(reply: RemoteResult<T>): T => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };

test('one collapsible course tree shares details with the map, without duplicate lessons or read side writes', async ({ page, classroom }, info) => {
  const client = await connectRuntime(classroom), errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const add = async (title: string, parent?: string) => value(await client.rpc<RouteView>('studyforgeOrganization/addRouteNode', { input: { operationId: title, node: { title, ...(parent ? { parent } : {}) } } }));
  const root = (await add('三角恒等变换')).nodes[0]!;
  const child = (await add('两角和差公式', root.id)).nodes[1]!;
  await add('配角与凑角', child.id);
  const other = (await add('独立的复习课')).nodes[3]!;
  value(await client.rpc('studyforgeOrganization/openPlannedLesson', { input: { operationId: 'open-one', nodeId: root.id } }));
  const stored = value(await client.rpc<RouteView>('studyforgeOrganization/route', {}));
  await page.setViewportSize({ width: 802, height: 747 }); await enterClassroom(page, classroom.authUrl);
  for (const style of ['modern', 'notebook'] as const) {
    await openAppearance(page); await page.getByTestId(`theme-${style}`).click(); await closeAppearance(page); await openCoursesList(page);
    const tree = page.getByTestId('roadmap-nodes');
    await expect(tree.getByTestId('roadmap-node-title')).toHaveText(['三角恒等变换', '独立的复习课']);
    await expect(tree.getByTestId('roadmap-node-edit')).toHaveCount(0);
    await expect(page.getByRole('heading', { name: '课堂记录', exact: true })).toHaveCount(0);
    await tree.getByRole('button', { name: '展开三角恒等变换', exact: true }).click();
    await expect(tree.getByTestId('roadmap-node-title')).toHaveText(['三角恒等变换', '两角和差公式', '独立的复习课']);
    await tree.getByRole('button', { name: '展开两角和差公式', exact: true }).click();
    await expect(tree.getByTestId('roadmap-node-title')).toHaveCount(4);
    await expect(tree.getByTestId('roadmap-node-title').first()).toHaveCSS('font-size', style === 'modern' ? '15px' : '16px');
    await page.screenshot({ path: info.outputPath(`${style}-course-tree-802.png`) });
    await tree.getByRole('button', { name: '查看三角恒等变换', exact: true }).click();
    const detail = page.getByTestId('course-node-detail');
    await expect(detail.getByRole('button', { name: '进入对话', exact: true })).toBeVisible();
    await detail.getByRole('button', { name: '课堂设置', exact: true }).click();
    await expect(page.getByTestId('lesson-settings-modal')).toBeVisible();
    await page.getByTestId('lesson-settings-close').click();
    await page.getByRole('button', { name: '关闭课程详情', exact: true }).click();
    await page.getByTestId('courses-view').selectOption('roadmap');
    await expect(page.getByTestId('roadmap-canvas-node')).toHaveCount(4);
    await page.getByTestId('courses-view').selectOption('list');
    await expect(tree.getByTestId('roadmap-node-title')).toHaveCount(4);
    await page.getByRole('searchbox', { name: '查找课程' }).fill('配角');
    await expect(tree.getByTestId('roadmap-node-title')).toHaveText(['三角恒等变换', '两角和差公式', '配角与凑角']);
    await page.getByRole('searchbox', { name: '查找课程' }).fill('');
    expect(value(await client.rpc<RouteView>('studyforgeOrganization/route', {}))).toEqual(stored);
    await page.setViewportSize({ width: 390, height: 844 });
    await tree.getByRole('button', { name: '查看独立的复习课', exact: true }).click();
    await expect(detail.getByRole('button', { name: '课堂设置', exact: true })).toBeInViewport();
    await detail.getByRole('button', { name: '课堂设置', exact: true }).click();
    await expect(page.getByTestId('route-editor')).toBeVisible();
    await expect(page.getByTestId('route-editor')).toHaveCSS('font-family', await tree.getByTestId('roadmap-node-title').first().evaluate(el => getComputedStyle(el).fontFamily));
    expect(await page.getByTestId('route-editor').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
    await page.screenshot({ path: info.outputPath(`${style}-course-settings-390.png`) });
    if (await page.getByTestId('notebook-sidebar').getAttribute('data-collapsed') !== 'true') await page.getByRole('button', { name: '收起侧栏', exact: true }).click();
    await expect.poll(async () => (await page.getByTestId('route-editor').boundingBox())?.width ?? 0).toBeGreaterThan(290);
    await page.screenshot({ path: info.outputPath(`${style}-course-settings-390-folded.png`) });
    await page.getByTestId('route-editor-cancel').click();
    await page.getByRole('button', { name: '关闭课程详情', exact: true }).click();
    await page.setViewportSize({ width: 802, height: 747 });
    await page.reload(); await openCoursesList(page);
  }
  await page.getByTestId('roadmap-node-title').filter({ hasText: '独立的复习课' }).click();
  await page.getByTestId('roadmap-node-mount').click();
  await page.getByTestId('roadmap-mount-select').selectOption({ label: '两角和差公式' });
  await expect.poll(async () => value(await client.rpc<RouteView>('studyforgeOrganization/route', {})).nodes.find(node => node.id === other.id)?.parent).toBe(child.id);
  expect(errors).toEqual([]);
});

test('opening early preserves the scheduled day and an opened course can be rescheduled from details', async ({ page, classroom }) => {
  const client = await connectRuntime(classroom);
  const route = value(await client.rpc<RouteView>('studyforgeOrganization/addRouteNode', { input: { operationId: 'future-course', node: { title: '将来的课程安排', date: '2027-03-05' } } }));
  const node = route.nodes[0]!;
  const opened = value(await client.rpc<{ sessionId: string }>('studyforgeOrganization/openPlannedLesson', { input: { operationId: 'early-open', nodeId: node.id } }));
  await enterClassroom(page, classroom.authUrl); await openCoursesList(page);
  await expect(page.getByTestId('roadmap-node-date')).toHaveText('3月5日');
  await page.locator('.sf-course-filters summary').click();
  await page.getByTestId('roadmap-filter-from').fill('2027-03-05');
  await page.getByTestId('roadmap-filter-to').fill('2027-03-05');
  await expect(page.getByTestId('roadmap-node-title')).toHaveText('将来的课程安排');
  await openCourseDetail(page, '将来的课程安排');
  await page.getByTestId('course-schedule-date').fill('2027-03-06');
  await page.getByTestId('course-schedule-save').click();
  await expect.poll(async () => value(await client.rpc<RouteView>('studyforgeOrganization/route', {})).nodes[0]?.date).toBe('2027-03-06');
  expect(value(await client.rpc<RouteView>('studyforgeOrganization/route', {})).nodes[0]?.session?.sessionId).toBe(opened.sessionId);
  await page.getByRole('button', { name: '关闭课程详情', exact: true }).click();
  await page.getByTestId('roadmap-filter-to').fill('2027-03-06'); await page.getByTestId('roadmap-filter-from').fill('2027-03-06');
  await expect(page.getByTestId('roadmap-node-title')).toHaveText('将来的课程安排');
  const day = value(await client.rpc<CalendarDay>('studyforgeCalendar/day', { query: { date: '2027-03-06', timeZone: 'Asia/Shanghai' } }));
  expect(day.scheduledCourses.map(course => course.target)).toContain('route:' + node.id);
});

test('a failed native lookup retains known planned and opened nodes and never adopts an incomplete write baseline', async ({ page, classroom }) => {
  const client = await connectRuntime(classroom);
  const route = value(await client.rpc<RouteView>('studyforgeOrganization/addRouteNode', { input: { operationId: 'retained-course', node: { title: '读取失败仍可回看的课' } } }));
  value(await client.rpc('studyforgeOrganization/openPlannedLesson', { input: { operationId: 'retained-open', nodeId: route.nodes[0]!.id } }));
  const before = value(await client.rpc<RouteView>('studyforgeOrganization/route', {}));
  await page.route('**/api/studyforgeOrganization/routeLessons', route => route.fulfill({ status: 503, body: 'Temporarily unavailable' }));
  await enterClassroom(page, classroom.authUrl); await openCoursesList(page);
  await expect(page.getByTestId('roadmap-node-title')).toHaveText('读取失败仍可回看的课');
  await expect(page.getByTestId('roadmap-notice')).toContainText('部分课堂信息');
  await expect(page.getByTestId('roadmap-create')).toBeDisabled();
  await openCourseDetail(page, '读取失败仍可回看的课');
  await expect(page.getByTestId('roadmap-node-open')).toBeEnabled();
  await expect(page.getByTestId('course-schedule-date')).toBeDisabled();
  await page.getByRole('button', { name: '关闭课程详情', exact: true }).click();
  await page.getByTestId('courses-view').selectOption('roadmap');
  await expect(page.getByTestId('roadmap-canvas-node').getByRole('button', { name: '进入对话', exact: true })).toBeEnabled();
  expect(value(await client.rpc<RouteView>('studyforgeOrganization/route', {}))).toEqual(before);
  await page.unroute('**/api/studyforgeOrganization/routeLessons');
  await page.getByTestId('roadmap-notice').getByRole('button', { name: '重试', exact: true }).click();
  await expect(page.getByTestId('roadmap-notice')).toHaveCount(0);
  await expect(page.getByTestId('roadmap-create')).toBeEnabled();
});

test('calendar groups real saved cards under their classroom and keeps outside notes separate in both themes', async ({ page, classroom }, info) => {
  test.setTimeout(120_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const client = await connectRuntime(classroom), date = civilDayIn('Asia/Shanghai');
  await enterClassroom(page, classroom.authUrl);
  await sendInput(page, '[tool]' + JSON.stringify({ name: 'propose_card', arguments: { kind: 'cards', title: '课堂题卡', cards: [
    { title: '用和差公式求目标角', front: '请先列出已知的角关系。' }, { title: '配角时的等价变形', front: '如何组合成目标角？' },
  ] } }));
  const proposal = page.getByTestId('inline-proposal').filter({ hasText: '课堂题卡' });
  await proposal.getByTestId('proposal-confirm-all').click();
  await expect.poll(async () => value(await client.rpc<CardView[]>('studyforgeLearning/cards', {})).length).toBe(2);
  const proposals = value(await client.rpc<ProposalView[]>('studyforgeProposals/list', { input: {} }));
  const origin = proposals[0]!.origin;
  if (origin.kind !== 'native') throw new Error('Expected a native classroom proposal');
  const sessionId = origin.sessionId;
  value(await client.rpc('session/rename', { request: { sessionId, title: '三角恒等变换专题' } }));
  value(await client.rpc<CardView>('studyforgeLearning/createCard', { input: { operationId: 'outside', content: { title: '课外整理的提醒', front: '先检查定义域。' } } }));
  const day = value(await client.rpc<CalendarDay>('studyforgeCalendar/day', { query: { date, timeZone: 'Asia/Shanghai' } }));
  expect(day.activity.filter(item => item.kind === 'card' && item.sourceRefs.includes('session:' + sessionId))).toHaveLength(2);
  for (const style of ['modern', 'notebook'] as const) {
    await page.setViewportSize({ width: 802, height: 747 });
    await openAppearance(page); await page.getByTestId(`theme-${style}`).click(); await closeAppearance(page); await openRoot(page, '日历');
    await page.getByRole('button', { name: '今天', exact: true }).click();
    const owner = page.getByTestId('calendar-activity-group').filter({ hasText: '三角恒等变换专题' });
    await expect(owner).toHaveCount(1);
    await expect(owner.getByTestId('calendar-activity-item').first()).toBeHidden();
    await owner.locator('summary').click();
    await expect(owner.getByTestId('calendar-activity-item')).toHaveCount(2);
    await expect(owner.getByTestId('calendar-activity-item').first()).toContainText('题卡');
    await expect(owner.getByTestId('calendar-activity-item').first().locator('button')).toHaveCSS('font-size', style === 'modern' ? '13px' : '15px');
    const outside = page.getByTestId('calendar-activity-group').filter({ hasText: '课外记录' });
    await outside.locator('summary').click();
    await expect(outside).toContainText('课外整理的提醒');
    await page.screenshot({ path: info.outputPath(`${style}-calendar-hierarchy-802.png`) });
    await owner.getByRole('button', { name: /用和差公式求目标角/ }).click();
    await expect(page.getByTestId('card-detail-title')).toContainText('用和差公式求目标角');
    await page.getByRole('button', { name: '关闭日期详情', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: '今天', exact: true }).click();
    await owner.locator('summary').click();
    await expect(owner.getByTestId('calendar-course')).toBeInViewport();
    expect(await page.getByTestId('calendar-detail').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
    await page.screenshot({ path: info.outputPath(`${style}-calendar-hierarchy-390.png`) });
    if (await page.getByTestId('notebook-sidebar').getAttribute('data-collapsed') !== 'true') await page.getByRole('button', { name: '收起侧栏', exact: true }).click();
    await expect.poll(async () => (await page.getByTestId('calendar-detail').boundingBox())?.width ?? 0).toBeGreaterThan(290);
    await page.screenshot({ path: info.outputPath(`${style}-calendar-hierarchy-390-folded.png`) });
    await page.getByRole('button', { name: '关闭日期详情', exact: true }).click();
  }
  expect(errors).toEqual([]);
});
