import { test, expect } from '@playwright/test';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { startVaultIsolated } from '../../scripts/dev-isolated.ts';

test('minimal assets, local graph and native split panes keep file and conversation context', async ({ page }, testInfo) => {
  test.setTimeout(180_000);
  const runtime = await startVaultIsolated();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  try {
    await mkdir(join(runtime.root, 'workspace/vault/卡片'), { recursive: true });
    await writeFile(join(runtime.root, 'workspace/vault/卡片/基底.md'), '---\ntype: card\ntags: [math, vector]\n---\n# 基底卡\n\n![[知识/向量.md#anchor=关键联系]]\n\n> 基底给出坐标的语言。\n');
    await writeFile(join(runtime.root, 'workspace/vault/卡片/坐标.md'), '---\ntype: card\nparent: 卡片/基底.md\ntags: [vector]\n---\n# 坐标卡\n\n![[卡片/基底.md#anchor=基底卡]]\n');
    await page.goto(runtime.authUrl);
    const later = page.getByRole('button', { name: 'Configure later', exact: true });
    try { await later.waitFor({ timeout: 8000 }); await later.click(); } catch { /* already acknowledged */ }
    await page.getByText('Notara Vault', { exact: true }).first().click();
    const input = page.locator('[data-composer-input][contenteditable="true"]').last();
    await input.fill('打开资料'); await input.press('Enter');
    await page.getByRole('tab', { name: '资产', exact: true }).click();
    await expect(page.getByRole('tab', { name: '阅读器', exact: true })).toHaveCount(0);
    await expect(page.getByText('文件事实源', { exact: true })).toHaveCount(0);
    await expect(page.getByRole('button', { name: '新建页面', exact: true })).toBeVisible();
    await expect(page.locator('[data-composer-input]')).toBeHidden();
    await page.getByRole('button', { name: '展开文件栏' }).click();
    await page.getByRole('button', { name: /向量\.md/ }).first().click();
    await expect(page.locator('.cm-vault-properties')).toBeVisible();
    await expect(page.locator('.cm-vault-properties dl')).toBeHidden();
    await page.getByRole('button', { name: '新建页面', exact: true }).click();
    await page.getByLabel('页面标题').fill('我的摘录');
    await page.getByLabel('目标路径').fill('卡片/我的摘录.md');
    await page.getByRole('button', { name: '创建 Markdown 页面', exact: true }).click();
    await expect(page.locator('.cm-content')).toContainText('我的摘录');
    expect(await readFile(join(runtime.root, 'workspace/vault/卡片/我的摘录.md'), 'utf8')).toContain('# 我的摘录');
    await page.getByRole('tab', { name: '图谱', exact: true }).click();
    await page.getByRole('button', { name: '图谱节点 向量', exact: true }).click();
    const details = page.getByRole('complementary', { name: '节点详情' });
    await expect(details).toContainText('子卡片 1');
    await expect(details.getByRole('button', { name: '基底卡', exact: true })).toBeVisible();
    await expect(details.getByText(/向量既可以用代数坐标/)).toHaveCount(0);
    await expect(details.getByRole('button', { name: '继续拆分', exact: true })).toHaveCount(0);
    await details.getByRole('button', { name: '以此为中心', exact: true }).click();
    await expect(page.getByRole('button', { name: '图谱节点 色板.svg', exact: true })).toHaveCount(0);
    await page.getByLabel('关联深度').selectOption('2');
    await expect(page.getByRole('button', { name: '图谱节点 坐标卡', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '标签筛选', exact: true }).click();
    await page.getByLabel('标签 math', { exact: true }).check();
    await expect(page.getByRole('button', { name: '图谱节点 坐标卡', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '标签筛选', exact: true }).click();
    await details.getByRole('button', { name: '带入对话拆分', exact: true }).click();
    await expect(page.locator('[data-nv-split]')).toBeVisible();
    await expect(page.locator('[data-composer-input]')).toHaveCount(1);
    await expect(page.locator('[data-composer-input]')).toBeVisible();
    await expect(page.locator('[data-composer-input]')).toContainText('拆分');
    await expect(page.locator('[data-nv-split]')).toContainText('向量');
    await expect(page.locator('[data-composer-input]')).toContainText('基底卡');
    const leftTabs = page.getByRole('tablist', { name: '左侧分页' });
    const rightTabs = page.getByRole('tablist', { name: '右侧分页' });
    const inputHandle = await page.locator('[data-composer-input]').elementHandle();
    const divider = page.getByRole('separator', { name: '调整分屏宽度' });
    await divider.focus(); await divider.press('ArrowLeft');
    await expect(divider).toHaveAttribute('aria-valuenow', '45');
    await page.getByRole('button', { name: '交换分屏', exact: true }).click();
    await expect(leftTabs.getByRole('tab', { name: '对话', exact: true })).toHaveAttribute('aria-selected', 'true');
    await expect(rightTabs.getByRole('tab', { name: '图谱', exact: true })).toHaveAttribute('aria-selected', 'true');
    // Bringing the right-hand source back to chat preserves that source pane.
    await leftTabs.getByRole('tab', { name: '卡片', exact: true }).click();
    await details.getByRole('button', { name: '带入对话拆分', exact: true }).click();
    await expect(leftTabs.getByRole('tab', { name: '对话', exact: true })).toHaveAttribute('aria-selected', 'true');
    await expect(rightTabs.getByRole('tab', { name: '图谱', exact: true })).toHaveAttribute('aria-selected', 'true');
    expect(await inputHandle!.evaluate(el => el === document.querySelector('[data-composer-input]'))).toBe(true);
    await rightTabs.getByRole('tab', { name: '轨迹', exact: true }).click();
    await expect(page.getByRole('region', { name: '轨迹区域' })).toBeVisible();
    await expect(page.locator('[data-composer-input]')).toHaveCount(1);
    await rightTabs.getByRole('tab', { name: '图谱', exact: true }).click();
    await page.screenshot({ path: testInfo.outputPath('split-chat-graph.png') });
    await page.getByRole('button', { name: '关闭分屏', exact: true }).click();
    await expect(page.locator('[data-nv-split]')).toHaveCount(0);
    await expect(page.locator('[data-composer-input]')).toContainText('拆分');
  } finally {
    await testInfo.attach('errors', { body: JSON.stringify(errors), contentType: 'application/json' });
    await runtime.stop();
  }
  expect(errors.filter(text => !/favicon|net::|downloadable font/i.test(text))).toEqual([]);
});
