import { openAppearance, closeAppearance } from './fixtures/classroom.ts';
import { test, expect, enterClassroom, sendInput, typeInput, openCards, openSetManagement } from './fixtures/classroom.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { CardView } from '@studyforge/contracts/cards';
import type { MaterialView } from '@studyforge/contracts/material-records';
import type { SessionListValue } from '@deepseek-ai/dsh-api-session-controller';

function value<T>(reply: RemoteResult<T>): T { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; }

test('notebook fonts, paper controls and browser routes preserve the actual native lesson and its draft', async ({ page, classroom }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await enterClassroom(page, classroom.authUrl);
  await expect(page.locator('body')).toHaveAttribute('data-sf-notebook', 'on');
  await sendInput(page, '求单调区间之前，我先把定义域写出来。');
  await expect(page.locator('[data-conversation-scroll]').getByText('已收到：求单调区间之前，我先把定义域写出来。', { exact: true })).toBeVisible();
  await page.evaluate(async () => { await document.fonts.load('18px "SF Long Cang"', '先看定义域'); await document.fonts.load('18px "SF Kalam"', 'abc'); });
  expect(await page.evaluate(() => document.fonts.check('18px "SF Long Cang"', '先看定义域'))).toBe(true);
  await expect(page.locator('[data-slot="main.conversation"] > [data-phase]')).toHaveCSS('background-image', /gradient/);
  await expect(page.locator('[data-composer-input]')).toHaveCSS('font-family', /SF Long Cang/);
  await expect(page.locator('[data-chat-flow-kind="assistant-step"] p').first()).toHaveCSS('font-family', /SF Long Cang/);
  await page.screenshot({ path: info.outputPath('notebook-classroom.png'), fullPage: true });
  await typeInput(page, '这条草稿和原来的课堂都保留。');
  await openAppearance(page);
  await expect(page.getByTestId('notebook-appearance')).toBeVisible();
  await expect.poll(async () => (await page.getByTestId('notebook-appearance').boundingBox())?.width ?? 0).toBeGreaterThan(290);
  expect(await page.getByTestId('notebook-appearance').evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await expect(page.getByTestId('notebook-appearance')).toBeVisible();
  await page.getByTestId('notebook-paper').selectOption('fangge');
  await page.getByTestId('notebook-tone').selectOption('white');
  await expect(page.getByTestId('notebook-appearance')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await expect(page.getByTestId('notebook-sidebar')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await page.getByTestId('notebook-scheme').selectOption('bing');
  await page.getByTestId('notebook-face').selectOption('hand');
  await page.getByTestId('notebook-size').selectOption('l');
  await page.evaluate(async () => { await document.fonts.load('18px "SF WenKai"', '先看定义域'); });
  await expect(page.locator('body')).toHaveAttribute('data-sf-paper', 'fangge');
  await page.screenshot({ path: info.outputPath('notebook-settings.png'), fullPage: true });
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(page.getByTestId('notebook-appearance')).toHaveCSS('background-color', 'rgb(40, 37, 31)');
  await page.screenshot({ path: info.outputPath('notebook-dark.png'), fullPage: true });
  await page.emulateMedia({ colorScheme: 'light' });
  await closeAppearance(page);
  await expect(page.locator('[data-composer-input]')).toContainText('这条草稿和原来的课堂都保留。');
  await openCards(page);
  await expect(page).toHaveURL(/#studyforge\/cards$/);
  await openAppearance(page);
  await expect(page.getByTestId('notebook-appearance')).toBeVisible();
  await page.reload();
  await openAppearance(page);
  await expect(page.getByTestId('notebook-tone')).toHaveValue('white');
  await expect(page.getByTestId('notebook-appearance')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await closeAppearance(page);
  await expect(page.getByTestId('studyforge-page-studyforge.cards')).toBeVisible();
  await page.getByRole('button', { name: '日历', exact: true }).first().click();
  await expect(page).toHaveURL(/#studyforge\/calendar$/);
  await page.goBack();
  await expect(page.getByTestId('studyforge-page-studyforge.cards')).toBeVisible();
  await page.goForward();
  await expect(page.getByTestId('studyforge-page-studyforge.calendar')).toBeVisible();
  await page.reload();
  await expect(page.getByTestId('studyforge-page-studyforge.calendar')).toBeVisible();
  await expect(page.locator('body')).toHaveAttribute('data-sf-scheme', 'bing');
  for (const [title, route] of [['首页','home'],['课程','courses'],['资料','materials'],['卡片','cards'],['学习集','sets'],['日历','calendar']] as const) {
    if (route === 'cards') await openCards(page);
    else if (route === 'sets') await openSetManagement(page);
    else await page.getByRole('button', { name: title, exact: true }).first().click();
    await expect(page).toHaveURL(new RegExp('#studyforge/' + (route === 'home' ? 'classroom' : route) + '$'));
    await expect(route === 'home' ? page.locator('[data-slot="main.conversation"]') : page.getByTestId('studyforge-page-studyforge.' + route)).toBeVisible();
    if (route === 'courses') {
      await expect(page.getByTestId('studyforge-page-studyforge.courses')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
      await expect(page.getByTestId('roadmap-canvas')).toHaveCSS('background-image', 'none');
    }
  }
  await openAppearance(page);
  await page.getByTestId('notebook-toggle').click();
  await expect(page.locator('body')).toHaveAttribute('data-sf-notebook', 'off');
  await page.getByTestId('notebook-toggle').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByTestId('notebook-appearance')).toBeVisible();
  await expect.poll(async () => (await page.getByTestId('notebook-appearance').boundingBox())?.width ?? 0).toBeGreaterThan(290);
  expect(await page.getByTestId('notebook-appearance').evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('notebook-390.png'), fullPage: true });
  const client = await connectRuntime(classroom);
  expect(value(await client.rpc<SessionListValue>('session/list', { _request: {} })).items.filter(row => !row.blank && row.origin !== 'subagent')).toHaveLength(1);
});

test('notebook card slips open the real card and its source returns to the originating lesson without recording study', async ({ page, classroom }, info) => {
  const client = await connectRuntime(classroom);
  await enterClassroom(page, classroom.authUrl);
  await sendInput(page, '从函数这一节开始。');
  await expect(page.locator('[data-conversation-scroll]').getByText('已收到：从函数这一节开始。', { exact: true })).toBeVisible();
  const book = value(await client.rpc<MaterialView>('studyforgeMaterials/import', { input: { operationId: 'notebook-book', material: { title: '函数笔记', fileName: '函数.md', mediaType: 'text/markdown' }, base64: Buffer.from('先写定义域，再讨论单调性。').toString('base64') } }));
  const source = { materialId: book.materialId, versionId: book.currentVersion.versionId, quote: '先写定义域', locator: { kind: 'text', start: { line: 1, column: 0 }, end: { line: 1, column: 5 } } };
  const card = value(await client.rpc<CardView>('studyforgeLearning/createCard', { input: { operationId: 'notebook-card', content: { title: '先写定义域', front: '讨论单调性之前，第一步写什么？', sources: [source] } } }));
  await openCards(page);
  await expect(page.getByTestId('card-row')).toHaveCount(1);
  await expect(page.locator('.sf-card-face-preview')).toContainText('讨论单调性');
  await page.evaluate(async () => { await document.fonts.load('24px "SF Long Cang"', '先写定义域'); });
  await page.screenshot({ path: info.outputPath('notebook-cards.png'), fullPage: true });
  await page.getByTestId('card-row-open').click();
  await expect(page.getByTestId('card-detail-title')).toHaveText(card.content.title);
  await page.getByTestId('card-detail-source-open').first().click();
  await expect(page.getByTestId('material-reader')).toBeVisible();
  await expect(page.getByTestId('source-highlight').first()).toBeVisible();
  await expect(page.getByTestId('material-return-lesson')).toBeVisible();
  await page.reload();
  await expect(page.getByTestId('source-highlight').first()).toBeVisible();
  await expect(page.getByTestId('material-return-lesson')).toBeVisible();
  await page.getByTestId('material-return-lesson').click();
  await expect(page.locator('[data-composer-input]')).toBeVisible();
  await expect(page.locator('[data-conversation-scroll]')).toContainText('从函数这一节开始。');
  await page.getByRole('button', { name: '资料', exact: true }).first().click();
  await expect(page.getByTestId('material-return-lesson')).toHaveCount(0);
  await page.goBack();
  await page.goBack();
  await expect(page.getByTestId('source-highlight').first()).toBeVisible();
  await expect(page.getByTestId('material-return-lesson')).toBeVisible();
  expect(value(await client.rpc<CardView>('studyforgeLearning/card', { input: { target: card.ref } })).history).toEqual([]);
});
