import { test, expect, enterClassroom, sendInput, typeInput } from './fixtures/classroom.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { SessionListValue } from '@deepseek-ai/dsh-api-session-controller';
import type { EvidenceCatalogue } from '../../packages/domain/src/evidence/evidence-query.ts';

test('native Queue, Steer, Stop and a later send keep one accepted input identity each', async ({ page, classroom }, testInfo) => {
  await enterClassroom(page, classroom.authUrl);
  const first = '[slow] 先逐步读这段话。'.repeat(12);
  await sendInput(page, first);
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeVisible();
  await typeInput(page, '换个例子继续');
  await page.getByRole('button', { name: 'Queue message', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Steer queued message', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Steer queued message', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toHaveCount(0, { timeout: 15_000 });
  await expect(page.locator('[data-conversation-scroll]').getByText('已收到：换个例子继续', { exact: true })).toHaveCount(1);
  const cancelled = '[slow] 这次先停一下。'.repeat(12);
  await sendInput(page, cancelled);
  const stop = page.getByRole('button', { name: 'Stop generating', exact: true });
  await expect(stop).toBeVisible(); await stop.click();
  await expect(stop).toHaveCount(0);
  await sendInput(page, '停下之后继续讨论');
  await expect(page.locator('[data-conversation-scroll]').getByText('已收到：停下之后继续讨论', { exact: true })).toHaveCount(1);
  const client = await connectRuntime(classroom);
  const list = await client.rpc<SessionListValue>('session/list', { _request: {} });
  expect(list.ok).toBe(true); if (!list.ok) return;
  const sessionId = list.value.items.find(row => !row.origin)?.sessionId;
  expect(sessionId).toBeTruthy();
  const evidence = await client.rpc<EvidenceCatalogue>('studyforgeCourses/evidence', { input: { sessionId } });
  expect(evidence.ok).toBe(true); if (!evidence.ok) return;
  expect(evidence.value.entries.map(entry => entry.quote)).toEqual([first, '换个例子继续', cancelled, '停下之后继续讨论']);
  expect(new Set(evidence.value.entries.map(entry => entry.messageId)).size).toBe(4);
  await page.screenshot({ path: testInfo.outputPath('native-control-recovery.png') });
  await page.reload();
  await expect(page.locator('[data-conversation-scroll]').getByText('已收到：停下之后继续讨论', { exact: true })).toHaveCount(1);
});

test('native Markdown streaming preserves completed nodes and does not pull a reader away from old text', async ({ page, classroom }, testInfo) => {
  await enterClassroom(page, classroom.authUrl);
  await sendInput(page, '[markdown] 先看这一段分式');
  const heading = page.getByRole('heading', { name: '分式与条件', exact: true });
  await expect(heading).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toHaveCount(0);
  await expect(page.locator('[data-conversation-scroll] code')).toContainText('先检查条件');
  const old = await heading.elementHandle();
  await sendInput(page, '[slow] 新的内容还在继续生成。'.repeat(18));
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeVisible();
  const scroller = page.locator('[data-conversation-scroll]');
  await scroller.hover(); await page.mouse.wheel(0, -6000);
  await expect.poll(() => scroller.evaluate(node => node.scrollTop)).toBeLessThan(10);
  await expect(heading).toBeInViewport();
  await page.waitForTimeout(500);
  expect(await scroller.evaluate(node => node.scrollTop)).toBeLessThan(10);
  expect(await old?.evaluate(node => node.isConnected)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('reading-old-math-during-stream.png') });
  await page.getByRole('button', { name: 'Stop generating', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toHaveCount(0);
  expect(await old?.evaluate(node => node.isConnected)).toBe(true);
});
