import { test, expect, enterClassroom, openRoot, openSetManagement } from './fixtures/classroom.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { SetView } from '@studyforge/contracts/sets';
import type { RouteView } from '@studyforge/contracts/routes';
import type { SessionListValue } from '@deepseek-ai/dsh-api-session-controller';
const value = <T,>(reply: RemoteResult<T>): T => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };

test('student set edits preserve their draft through a real concurrent update and persist at narrow width', async ({ page, classroom }, info) => {
  const client = await connectRuntime(classroom);
  await enterClassroom(page, classroom.authUrl);
  await openSetManagement(page);
  await page.getByRole('button', { name: '新建学习集', exact: true }).click();
  await page.getByLabel('学习集名称').fill('期末复习');
  await page.getByLabel('复习间隔', { exact: true }).fill('1, 3, 7');
  await page.getByRole('button', { name: '保存学习集', exact: true }).click();
  await expect(page.getByRole('heading', { name: '期末复习', exact: true })).toBeVisible();
  const before = value(await client.rpc<SetView[]>('studyforgeOrganization/sets', { input: {} }))[0]!;
  await page.getByRole('button', { name: '调整学习集', exact: true }).click();
  await page.getByLabel('学习集名称').fill('我的合并草稿');
  value(await client.rpc<SetView>('studyforgeOrganization/updateSet', { input: { ref: before.ref, expectedVersion: before.version, operationId: 'concurrent', patch: { name: '老师新版' } } }));
  await page.getByRole('button', { name: '保存学习集', exact: true }).click();
  await expect(page.getByText('新版：老师新版', { exact: false })).toBeVisible();
  await expect(page.getByLabel('学习集名称')).toHaveValue('我的合并草稿');
  await page.getByRole('button', { name: '已核对，保留草稿继续合并' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(async () => (await page.getByTestId('set-editor').boundingBox())?.width ?? 0).toBeGreaterThan(250);
  await page.getByRole('button', { name: '保存学习集', exact: true }).click();
  await expect(page.getByRole('heading', { name: '我的合并草稿' })).toBeVisible();
  expect(value(await client.rpc<SetView>('studyforgeOrganization/set', { input: { ref: before.ref } })).name).toBe('我的合并草稿');
  await page.screenshot({ path: info.outputPath('set-narrow.png'), fullPage: true });
});

test('calendar opens date details in a recoverable right pane and keeps review plans reachable', async ({ page, classroom }, info) => {
  const client = await connectRuntime(classroom), date = '2026-09-20';
  for (const title of ['第一节课', '第二节课']) value(await client.rpc<RouteView>('studyforgeOrganization/addRouteNode', { input: { operationId: title, node: { title, date } } }));
  await enterClassroom(page, classroom.authUrl);
  await openRoot(page, '日历');
  await expect(page.getByText('定时日报', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '查看日报' })).toHaveCount(0);
  await page.getByRole('button', { name: '今天', exact: true }).click();
  await page.getByLabel('查看日期').fill(date);
  await expect(page.getByTestId('calendar-course')).toHaveCount(2);
  await expect(page.getByTestId('calendar-due')).toContainText('0 张');
  const lesson = page.getByTestId('calendar-activity-group').filter({ hasText: '第二节课' });
  await lesson.locator('summary').click();
  await lesson.getByTestId('calendar-course').click();
  await expect(page.locator('[data-composer-input]')).toBeVisible();
  const route = value(await client.rpc<RouteView>('studyforgeOrganization/route', {}));
  expect(route.nodes.find(node => node.title === '第一节课')?.session).toBeUndefined();
  expect(route.nodes.find(node => node.title === '第二节课')?.session?.sessionId).toBeTruthy();
  const sessions = value(await client.rpc<SessionListValue>('session/list', { _request: {} }));
  expect(sessions.items.some(item => item.sessionId === route.nodes[1]?.session?.sessionId)).toBe(true);
  await page.getByRole('button', { name: '日历', exact: true }).first().click();
  await page.getByRole('button', { name: '今天', exact: true }).click();
  await expect(page.getByRole('complementary', { name: '当天安排' })).toBeVisible();
  await page.getByRole('button', { name: '关闭日期详情' }).click();
  await expect(page.getByTestId('calendar-detail')).toHaveCount(0);
  await page.getByTestId('calendar-cell').filter({ hasText: '20' }).first().click();
  await expect(page.getByTestId('calendar-day')).toBeVisible();
  await page.screenshot({ path: info.outputPath('calendar-day-pane.png'), fullPage: true });
  await page.getByTestId('calendar-review-plans').click();
  await expect(page.getByTestId('plan-create-campaign')).toBeVisible();
  await page.getByTestId('plan-create-campaign').click();
  await expect(page.getByTestId('plan-editor')).toBeVisible();
  await page.setViewportSize({ width: 500, height: 800 });
  expect(await page.getByTestId('calendar-detail').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
});
