import type {Context} from '@deepseek-ai/cordis';
import {useEffect,useState} from 'react';
import type {WorkbenchContent} from '@studyforge/contracts/plugins';
import type {PluginLink} from '@studyforge/contracts/plugin-learning';
export function PluginSourcePicker({ctx,sessionId,content,done}:{ctx:Context;sessionId:string;content:WorkbenchContent;done:(link?:PluginLink)=>void}):React.JSX.Element{
 const [query,setQuery]=useState(''),[rows,setRows]=useState<PluginLink[]>([]),[notice,setNotice]=useState(''),[page,setPage]=useState('');
 useEffect(()=>{let live=true;void ctx.remote.notaraWorkbench.sources({sessionId,id:content.id,digest:content.digest,query}).then(r=>{if(live){if(r.ok)setRows(r.value);else setNotice('资料暂时无法读取，请重试。');}}).catch(()=>{if(live)setNotice('资料暂时无法读取。');});return()=>{live=false;};},[ctx,sessionId,content,query]);
 return <section className="sf-plugin-note" role="dialog" aria-modal="true" aria-label="选择资料来源"><h3>选择资料来源</h3><label>搜索标题<input value={query} onChange={e=>setQuery(e.target.value)} autoFocus /></label><label>PDF页码（可选）<input type="number" min="1" value={page} onChange={e=>setPage(e.target.value)} /></label><div style={{overflow:'auto',flex:1}}>{rows.map((link,index)=><button key={index} className="sf-plugin-row" onClick={()=>{if(page&&(!Number.isSafeInteger(Number(page))||Number(page)<1)){setNotice('请输入有效页码。');return;}const picked:PluginLink=link.kind==='source'&&page?{...link,source:{...link.source,locator:{kind:'pdf',page:Number(page)}}}:link;void ctx.remote.notaraWorkbench.resolveLink({sessionId,id:content.id,digest:content.digest,link:picked}).then(result=>{if(result.ok)done(result.value);else setNotice('这个定位无法打开，请核对资料类型和页码。');}).catch(()=>setNotice('资料暂时无法打开，请重试。'));}}><span>{link.title}</span><small>{link.kind==='source'?'原文':link.kind==='card'?'卡片':'课堂'}</small></button>)}</div><p role="status">{notice||(!rows.length?'没有匹配的资料':rows.length===60?'显示前60项，可继续输入标题缩小范围。':'')}</p><button className="sf-quiet" onClick={()=>done()}>取消</button></section>;
}
