import { afterEach, expect, test } from 'vitest';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { ArtifactView, ArtifactInstallation } from '@studyforge/contracts/creation';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
const value = <T>(r: RemoteResult<T>): T => { if (!r.ok) throw new Error(JSON.stringify(r.error)); return r.value; };
test('installation pins bytes, publishes handouts atomically, rejects stale changes and removes disabled skill entries', async () => {
  runtime = await startIsolated({ testModel: true }); const client = await connectRuntime(runtime);
  const create = async (kind: string, title: string) => value(await client.rpc<ArtifactView>('studyforgeCreation/create', { input: { operationId: title, kind, title, references: [], content: '# ' + title + '\n一步一步解释。' } }));
  const skill = await create('skill', '追问三个为什么');
  const install = (v: ArtifactView, expectedVersion = 0) => client.rpc<ArtifactInstallation>('studyforgeCreation/publishArtifact', { input: { ref: v.ref, digest: v.digest, operationId: 'install:' + v.digest, expectedVersion } });
  const installed = value(await install(skill)); expect(value(await install(skill)).revision).toBe(installed.revision);
  expect(JSON.stringify(value(await client.rpc('studyforgeTeaching/tasks', {})))).toContain('追问三个为什么');
  const f = skill.files.find(f => f.path === 'content.md')!;
  const changed = value(await client.rpc<ArtifactView>('studyforgeCreation/save', { input: { ref: skill.ref, path: f.path, expectedDigest: f.digest, content: '新正文' } }));
  expect((await install(skill, installed.revision)).ok).toBe(false);
  expect((await install(changed, 0)).ok).toBe(false);
  value(await client.rpc('studyforgeCreation/setEnabled', { input: { ref: skill.ref, expectedVersion: installed.revision, operationId: 'disable', enabled: false } }));
  expect(JSON.stringify(value(await client.rpc('studyforgeTeaching/tasks', {})))).not.toContain('追问三个为什么');
  const handout = await create('markdown', '能量守恒讲义');
  const published = value(await install(handout)); expect(published.publication?.ref).toMatch(/^material:/);
  expect(value(await install(handout)).publication).toEqual(published.publication);
  const file = handout.files.find(f => f.path === 'content.md')!;
  const revision = value(await client.rpc<ArtifactView>('studyforgeCreation/save', { input: { ref: handout.ref, path: file.path, expectedDigest: file.digest, content: '新讲义' } }));
  expect((await install(revision, 0)).ok).toBe(false);
  const materials = value(await client.rpc<any[]>('studyforgeMaterials/list', {}));
  expect(materials.find(m => 'material:' + m.materialId === published.publication?.ref)?.revision).toBe(1);
  await runtime.restart();
  const resumed = await connectRuntime(runtime);
  expect(value(await resumed.rpc<ArtifactView>('studyforgeCreation/read', { input: { ref: handout.ref } })).digest).toBe(revision.digest);
}, 45_000);

test('installed subject text stays pinned in an existing lesson when the creator publishes a later version', async () => {
  runtime = await startIsolated({ testModel: true }); const client = await connectRuntime(runtime);
  let subject = value(await client.rpc<ArtifactView>('studyforgeCreation/create', { input: { operationId: 'subject', title: '物理教法', kind: 'subject', subjects: ['物理'], references: [], content: '版本一：先画系统边界再讨论能量。' } }));
  const publish = (expectedVersion: number) => client.rpc<ArtifactInstallation>('studyforgeCreation/publishArtifact', { input: { ref: subject.ref, digest: subject.digest, operationId: 'install:' + subject.digest, expectedVersion } }).then(value);
  const installed = await publish(0);
  const open = () => client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}).then(value);
  const a = await open(); value(await client.rpc('studyforgeCourses/update', { input: { ...a, operationId: 'a-subject', expectedVersion: 0, patch: { subjects: ['物理'] } } }));
  const ask = async (sessionId: string, text: string) => { value(await client.rpc('session/prompt', { request: { sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text }] } })); await expect.poll(async () => (await readFile(join(runtime!.root, 'model-requests.jsonl'), 'utf8').catch(() => '')).trim().split('\n').filter(Boolean).map(line => JSON.parse(line)).some(row => row.sessionId === sessionId && row.purpose !== 'session-title' && JSON.stringify(row.messages).includes(text))).toBe(true); };
  await ask(a.sessionId, '先上第一轮物理');
  const file = subject.files.find(file => file.path === 'content.md')!;
  subject = value(await client.rpc<ArtifactView>('studyforgeCreation/save', { input: { ref: subject.ref, path: file.path, expectedDigest: file.digest, content: '版本二：先观察运动再选定系统。' } }));
  await publish(installed.revision);
  await ask(a.sessionId, '接着上第二轮物理');
  const requests = (await readFile(join(runtime.root, 'model-requests.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
  expect(JSON.stringify(requests.filter(row => row.sessionId === a.sessionId && row.purpose !== 'session-title').at(-1))).toContain('版本一');
  expect(JSON.stringify(requests.filter(row => row.sessionId === a.sessionId && row.purpose !== 'session-title').at(-1))).not.toContain('版本二');
  const b = await open(); value(await client.rpc('studyforgeCourses/update', { input: { ...b, operationId: 'b-subject', expectedVersion: 0, patch: { subjects: ['物理'] } } })); await ask(b.sessionId, '新课使用当前教法');
  const updated = (await readFile(join(runtime.root, 'model-requests.jsonl'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
  expect(JSON.stringify(updated.filter(row => row.sessionId === b.sessionId && row.purpose !== 'session-title').at(-1))).toContain('版本二');
}, 45000);
