import { afterEach, expect, test } from 'vitest';
import { readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { ArtifactView, ArtifactInstallation } from '@studyforge/contracts/creation';
import type { WorldbookView, PluginCandidate, PluginView, WorkbenchContent } from '@studyforge/contracts/plugins';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
const value = (reply: any): any => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };

test('classroom creator shares validated files with AI, preserves concurrent edits and installs through the plugin pipeline', async () => {
  runtime = await startIsolated({ testModel: true }); let client = await connectRuntime(runtime);
  const candidate = value(await client.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path: resolve('examples/plugins/worldbook') } }));
  const plugin = value(await client.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: candidate.candidateId, expectedVersion: 0, trustNative: false } }));
  const teacher = value(await client.rpc('studyforgeCreation/openTeacher', {}));
  const seed = value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: { ...teacher, id: 'plugin-' + plugin.ref.slice(7) + '-worldbook' } }));
  expect(seed.document.entries).toEqual([]); expect(seed.document.classroom.roles).toEqual([]); expect(seed.document.classroom.rules).toEqual([]);
  const templates = value(await client.rpc('studyforgeCreation/classroomTemplates', {})); expect(templates).toHaveLength(3);
  let project = value(await client.rpc<ArtifactView>('studyforgeCreation/create', { input: { title: '我的教室', kind: 'classroom', operationId: 'create-room', references: [] } }));
  expect(value(await client.rpc('studyforgeCreation/openCreator', { input: { ref: project.ref } })).sessionId).toBe(project.sessionId);
  expect(value(await client.rpc('session/list', { _request: {} })).items.find((item: any) => item.sessionId === project.sessionId).projections.values.agentPreset).toBe('studyforge-creation');
  expect(value(await client.rpc('skills/list', { request: { sessionId: project.sessionId } })).skills.some((item: any) => item.description.includes('共同设计成员'))).toBe(true);
  expect(value(await client.rpc('skills/list', { request: teacher })).skills.some((item: any) => item.description.includes('共同设计成员'))).toBe(false);
  const read = async (): Promise<ArtifactView> => value(await client.rpc<ArtifactView>('studyforgeCreation/read', { input: { ref: project.ref } }));
  const document = JSON.parse(templates[1].content); document.classroom.title = '共建推理教室';
  const send = async (sessionId: string, calls: unknown[]): Promise<void> => {
    const log = async () => (await readFile(join(runtime!.root, 'model-requests.jsonl'), 'utf8').catch(() => '')).split('\n').filter(Boolean).map(line => JSON.parse(line)).filter(row => row.sessionId === sessionId);
    const before = (await log()).length;
    value(await client.rpc('session/prompt', { request: { sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '[tools]' + JSON.stringify(calls) }] } }));
    await expect.poll(async () => (await log()).length, { timeout: 15000 }).toBeGreaterThan(before);
    await expect.poll(async () => value(await client.rpc('session/list', { _request: {} })).items.find((item: any) => item.sessionId === sessionId)?.running, { timeout: 30000 }).toBe(false);
  };
  await send(project.sessionId, [{ name: 'read_classroom_draft', arguments: {} }, { name: 'save_classroom_draft', arguments: { document } }]);
  project = await read(); expect(JSON.parse(project.files.find((file: any) => file.path === 'worldbook.json').body).classroom.title).toBe('共建推理教室');
  const requests = await readFile(join(runtime.root, 'model-requests.jsonl'), 'utf8'); expect(requests).toContain('共建教室');
  const nativePath = 'packs/work-' + project.ref.slice(9) + '/worldbook.json';
  await send(project.sessionId, [{ name: 'read', arguments: { file_path: nativePath } }, { name: 'write', arguments: { file_path: nativePath, content: '{"entries":[]}' } }]);
  expect((await read()).digest).toBe(project.digest);
  await send(project.sessionId, [{ name: 'read_classroom_draft', arguments: {} }]);
  const file = project.files.find((file: any) => file.path === 'worldbook.json');
  const studentEdit = structuredClone(document); studentEdit.entries = [{ title: '面板编辑', content: '保留我的改动', keywords: [], always: true, enabled: true }];
  value(await client.rpc('studyforgeCreation/save', { input: { ref: project.ref, path: 'worldbook.json', expectedDigest: file.digest, content: JSON.stringify(studentEdit) } }));
  await send(project.sessionId, [{ name: 'save_classroom_draft', arguments: { document } }]);
  project = await read(); expect(JSON.parse(project.files.find((file: any) => file.path === 'worldbook.json').body)).toEqual(studentEdit);
  const bad = structuredClone(studentEdit); bad.classroom.rules = [{ id: 'bad', title: 'bad', enabled: true, trigger: { kind: 'manual' }, action: { kind: 'classmate', roleId: 'missing', task: 'task', materials: ['words'], destination: 'conversation' } }];
  expect((await client.rpc('studyforgeCreation/save', { input: { ref: project.ref, path: 'worldbook.json', expectedDigest: project.files.find((file: any) => file.path === 'worldbook.json').digest, content: JSON.stringify(bad) } })).ok).toBe(false);
  const installed = value(await client.rpc<ArtifactInstallation>('studyforgeCreation/publishArtifact', { input: { ref: project.ref, digest: project.digest, operationId: 'install', expectedVersion: 0 } })); expect(installed.kind).toBe('classroom');
  const packages = value(await client.rpc<PluginView[]>('studyforgePlugins/list', {}));
  const own = packages.find((item: PluginView) => item.creationRef === project.ref); expect(own.manifest.notara.worldbooks).toHaveLength(1); expect(own.native).toBe(false);
  const lesson = value(await client.rpc('studyforgeCreation/openTeacher', {})), target = { ...lesson, id: 'plugin-' + own.ref.slice(7) + '-main' };
  expect(value(await client.rpc<WorkbenchContent>('studyforgePlugins/openWorkbench', { input: target })).kind).toBe('classroom');
  const inClass = value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: target })); expect(inClass.document).toEqual(studentEdit); expect(inClass.enabled).toBe(false);
  await runtime.restart(); client = await connectRuntime(runtime);
  expect((await read()).digest).toBe(project.digest);
  value(await client.rpc('studyforgePlugins/setEnabled', { input: { ref: plugin.ref, expectedVersion: plugin.revision, enabled: false } }));
  expect(value(await client.rpc('studyforgeCreation/classroomTemplates', {}))).toEqual([]);
}, 120000);
