import { afterEach, expect, test } from 'vitest';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { ClassroomTrace } from '@studyforge/contracts/classroom-trace';
import type { CourseView } from '@studyforge/contracts/courses';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
let runtime: IsolatedRuntime | undefined; afterEach(async () => { await runtime?.stop(); });
const value = <T>(r: RemoteResult<T>): T => { if (!r.ok) throw new Error(JSON.stringify(r.error)); return r.value; };
test('thought nodes bind actual messages, edits survive restart, cycles fail and native forks do not duplicate inherited nodes', async () => {
  runtime = await startIsolated({ testModel: true }); let client = await connectRuntime(runtime);
  const { sessionId } = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  value(await client.rpc('studyforgeCourses/update', { input: { sessionId, operationId: 'course', expectedVersion: 0, patch: { subjects: ['物理'], teachingRef: 'feynman' } } }));
  value(await client.rpc('session/prompt', { request: { sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '为什么能量守恒？' }] } }));
  await expect.poll(async () => (await readFile(join(runtime!.root, 'model-requests.jsonl'), 'utf8').catch(() => '')).includes('为什么能量守恒')).toBe(true);
  const read = () => client.rpc<ClassroomTrace>('studyforgeTrace/read', { input: { sessionId } }).then(value);
  await expect.poll(async () => (await read()).nodes.some(n => n.kind === 'answer')).toBe(true);
  let graph = await read(); const original = graph.nodes[0]!;
  graph = value(await client.rpc<ClassroomTrace>('studyforgeTrace/edit', { input: { sessionId, expectedVersion: graph.version, operationId: 'note', node: { title: '先界定系统', body: '边界决定能否使用守恒。', kind: 'idea', sequence: original.sequence, position: { x: 350, y: 180 } } } }));
  const note = graph.nodes.find(n => n.title === '先界定系统')!;
  graph = value(await client.rpc<ClassroomTrace>('studyforgeTrace/edit', { input: { sessionId, expectedVersion: graph.version, operationId: 'edge', edge: { from: original.id, to: note.id, label: '需要先确定' } } }));
  expect((await client.rpc('studyforgeTrace/edit', { input: { sessionId, expectedVersion: graph.version, operationId: 'cycle', edge: { from: note.id, to: original.id, label: '循环' } } })).ok).toBe(false);
  expect((await client.rpc('studyforgeTrace/edit', { input: { sessionId, expectedVersion: 0, operationId: 'stale', node: { id: note.id, title: '覆盖', body: '', kind: 'idea' } } })).ok).toBe(false);
  const child = value(await client.rpc<{ sessionId: string }>('studyforgeTrace/fork', { input: { sessionId, atSeq: original.sequence } }));
  const fork = value(await client.rpc<ClassroomTrace>('studyforgeTrace/read', { input: child }));
  expect(fork.parent).toBe(sessionId); expect(fork.nodes).toHaveLength(0);
  const unrelated = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  const family = await read();
  expect(family.branches.map(item => item.sessionId).sort()).toEqual([sessionId, child.sessionId].sort());
  expect(family.branches.some(item => item.sessionId === unrelated.sessionId)).toBe(false);
  expect(value(await client.rpc<CourseView>('studyforgeCourses/read', { input: child })).data).toMatchObject({ closure: null, subjects: ['物理'], teachingRef: 'feynman' });
  await runtime.restart(); client = await connectRuntime(runtime);
  expect((await read()).nodes.find(n => n.id === note.id)?.position).toEqual({ x: 350, y: 180 });
}, 45_000);
