import { afterEach, expect, test } from 'vitest';
import { join } from 'node:path';
import { readFile } from 'node:fs/promises';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { ResolvedEntityReference } from '../../packages/contracts/src/entity-reference.ts';
import { entityReferenceContent } from '../../packages/host/src/tools/entity-reference-output.ts';
import { parseEntityHref, entityLink } from '../../packages/contracts/src/entity-reference.ts';
import { turn, nativeEvents } from '../fixtures/live-classroom.ts';
let runtime:IsolatedRuntime|undefined;
afterEach(async()=>{await runtime?.stop();runtime=undefined;});
function value<T>(r:RemoteResult<T>):T{if(!r.ok)throw new Error(JSON.stringify(r.error));return r.value;}
test('real stored references preserve old cards, knowledge, sections and source ranges after update and restart without learning writes',async()=>{
  runtime=await startIsolated({testModel:true});let client=await connectRuntime(runtime);
  const call=async<T=any>(method:string,input:unknown)=>value(await client.rpc<T>(method,{input}));
  const book=await call('studyforgeMaterials/import',{operationId:'ref-book',material:{title:'引用讲义',fileName:'引用讲义.md',mediaType:'text/markdown'},base64:Buffer.from('# 第一章\n例2的原文\n例7的原文\n').toString('base64')});
  const {sessionId}=value(await client.rpc<{sessionId:string}>('session/create',{request:{cwd:join(runtime.root,'classroom'),agentPreset:'studyforge-learning'}}));
  const source={materialId:book.materialId,versionId:book.currentVersion.versionId,locator:{kind:'text',start:{line:2,column:0},end:{line:2,column:5}}};
  const skeleton=await call('studyforgeOrganization/saveSkeleton',{operationId:'ref-skeleton',materialId:book.materialId,expectedVersion:0,change:{nodes:[{path:'数学/例2',sources:[source]}]}});
  const card=await call('studyforgeLearning/createCard',{operationId:'ref-card',content:{title:'例2',front:'第一版题面',chapter:'数学/例2',sources:[{...source,quote:'例2的原文'}]}});
  const note=await call('studyforgeLearning/noteMethod',{operationId:'ref-note',content:{title:'方法',body:'第一版方法'}});
  const cardRef={kind:'card',ref:card.ref,version:card.version};
  const refs=[cardRef,{kind:'knowledge',ref:note.ref,version:note.version},{kind:'section',materialId:book.materialId,skeletonRevision:skeleton.revision,path:'数学/例2'},{kind:'source',source}];
  for(const reference of refs) expect((await call<ResolvedEntityReference>('studyforgeLibrary/resolveReference',{sessionId,reference})).reference).toEqual(reference);
  expect((await call<ResolvedEntityReference>('studyforgeLibrary/resolveReference',{sessionId,reference:cardRef})).sources).toEqual([source]);
  const generated=entityReferenceContent({cards:[card],hits:[{corpus:'knowledge',ref:note.ref,revision:note.version,title:note.content.title}]});
  const links=generated.flatMap(b=>b.type==='text'?[...b.text.matchAll(/\]\((#studyforge\/reference\/[A-Za-z0-9_-]+)\)/g)].map(m=>parseEntityHref(m[1]!)):[]);
  expect(links).toHaveLength(3);expect(links).toEqual(expect.arrayContaining([cardRef,refs[1],refs[3]]));
  await call('studyforgeLearning/editCard',{operationId:'ref-card-edit',target:card.ref,expectedVersion:card.version,patch:{title:'改名后的例2',front:'第二版题面'}});
  await call('studyforgeOrganization/saveSkeleton',{operationId:'ref-skeleton-edit',materialId:book.materialId,expectedVersion:skeleton.revision,change:{nodes:[{path:'数学/例7',sources:[{...source,locator:{...source.locator,start:{line:3,column:0},end:{line:3,column:5}}}]}]}});
  const before=await readFile(join(runtime.root,'classroom/.studyforge/sf_records.json'),'utf8');
  expect(await call('studyforgeLibrary/resolveReference',{sessionId,reference:cardRef})).toMatchObject({title:'例2',historical:true});
  expect(await call('studyforgeLibrary/resolveReference',{sessionId,reference:refs[2]})).toMatchObject({chapter:'数学/例2',historical:true});
  expect((await client.rpc('studyforgeLibrary/resolveReference',{input:{sessionId,reference:{kind:'source',source:{...source,locator:{...source.locator,start:{line:900,column:0},end:{line:900,column:1}}}}}})).ok).toBe(false);
  expect((await client.rpc('studyforgeLibrary/resolveReference',{input:{sessionId:'not-this-workspace',reference:cardRef}})).ok).toBe(false);
  expect((await client.rpc('studyforgeLibrary/resolveReference',{input:{sessionId,reference:{...cardRef,version:999}}})).ok).toBe(false);
  expect(await readFile(join(runtime.root,'classroom/.studyforge/sf_records.json'),'utf8')).toBe(before);
  await runtime.restart();client=await connectRuntime(runtime);
  expect(await call('studyforgeLibrary/resolveReference',{sessionId,reference:cardRef})).toMatchObject({title:'例2',historical:true});
  expect(await readFile(join(runtime.root,'classroom/.studyforge/sf_records.json'),'utf8')).toBe(before);
  const classroom = { runtime, client, stop: () => runtime!.stop() };
  const link = entityLink('例2', { kind: 'card', ref: card.ref, version: card.version });
  const reply = await turn(classroom, sessionId, '请对照' + link + '。');
  const trace = await call<any>('studyforgeTrace/read', { sessionId });
  expect(trace.nodes.map((node:any) => node.title).join(' ')).not.toContain('#studyforge/reference');
  const fork = await call<{sessionId:string}>('studyforgeTrace/fork', { sessionId, atSeq: reply.anchor });
  const inherited = await nativeEvents(classroom, { kind: 'session', sessionId: fork.sessionId });
  expect(JSON.stringify(inherited)).toContain(link);
  expect(await call('studyforgeLibrary/resolveReference', { sessionId: fork.sessionId, reference: cardRef })).toMatchObject({ title: '例2', historical: true });
},45000);
