import { afterEach, expect, test } from 'vitest';
import { resolve } from 'node:path';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { SessionListValue, SessionPage } from '@deepseek-ai/dsh-api-session-controller';
import type { PluginCandidate, PluginView } from '@studyforge/contracts/plugins';
import type { ClassroomTrace } from '@studyforge/contracts/classroom-trace';
import type { CardView } from '@studyforge/contracts/cards';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
function value<T>(reply: RemoteResult<T>): T { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; }
test('math document round-trip, successful note stages, summaries, conflicts and restart use the same records', async () => {
  runtime = await startIsolated({ testModel: true }); let client = await connectRuntime(runtime);
  const candidate = value(await client.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path: resolve('examples/plugins/math-workbench') } }));
  const plugin = value(await client.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: candidate.candidateId, expectedVersion: 0, trustNative: false } }));
  const session = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  const target = { ...session, id: 'plugin-' + plugin.ref.slice(7) + '-board', digest: plugin.digest };
  const read = () => client.rpc<{ revision: number; json: string }>('notaraWorkbench/readDocument', { input: target }).then(value);
  const trace = () => client.rpc<ClassroomTrace>('studyforgeTrace/read', { input: session }).then(value);
  async function tool(name: string, args: unknown) {
    value(await client.rpc('session/prompt', { request: { ...session, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '[tool]' + JSON.stringify({ name, arguments: args }) }] } }));
    await expect.poll(async () => value(await client.rpc<SessionListValue>('session/list', { _request: {} })).items.find(row => row.sessionId === session.sessionId)?.running).toBe(false);
    const end = await client.rpc<SessionPage>('session/page', { request: { address: { kind: 'session', ...session }, throughSeq: 1_000_000, maxMessages: 1 } });
    const cursor = end.ok ? -1 : Number(/past cursor (-?\d+)/.exec(end.error.message)?.[1] ?? -1);
    const page = value(await client.rpc<SessionPage>('session/page', { request: { address: { kind: 'session', ...session }, throughSeq: cursor, maxMessages: 300 } }));
    const record = page.records.filter(r => r.type === 'event' && r.event.type === 'tool/result').at(-1);
    if (!record || record.type !== 'event') throw new Error('tool_result_missing');
    const block = (record.event.data as { message: { content: { isError?: boolean; content: { text?: string }[] }[] } }).message.content[0]!;
    return { failed: !!block.isError, text: block.content.find(c => c.text)?.text ?? '' };
  }
  const blank = JSON.parse((await read()).json);
  const document = { ...blank, title: '导数的局部意义', parameters: [{ name: 'a', value: 1, min: -3, max: 3, step: .1 }], objects: [{ kind: 'function', name: 'f', expression: 'a*x^2' }, { kind: 'glider', name: 'P', curve: 'f', x: 1 }, { kind: 'tangent', name: 'tangent', point: 'P' }] };
  expect((await tool('update_workbench', { id: target.id, expectedVersion: 0, documentJson: JSON.stringify(document) })).failed).toBe(false);
  const current = await read(); expect(current.revision).toBe(1);
  const studentEdit = JSON.parse(current.json); studentEdit.parameters[0].value = 2; studentEdit.observation = '同一点的斜率变了。';
  value(await client.rpc('notaraWorkbench/writeDocument', { input: { ...target, expectedVersion: 1, operationId: 'student-change', json: JSON.stringify(studentEdit) } }));
  expect((await tool('read_workbench', { id: target.id })).text).toContain('同一点的斜率变了');
  expect((await tool('update_workbench', { id: target.id, expectedVersion: 1, documentJson: JSON.stringify(document) })).failed).toBe(true);
  expect((await trace()).stages.filter(s => !s.stage.pending)).toHaveLength(0);
  const noteInput = { ...target, operationId: 'confirmed-note', note: { title: '图像斜率观察', body: 'a = 2，同一点的斜率变了。', documentRevision: 2 } };
  expect((await client.rpc('studyforgePlugins/saveNote', { input: { ...noteInput, note: { ...noteInput.note, documentRevision: 1 } } })).ok).toBe(false);
  const note = value(await client.rpc<CardView>('studyforgePlugins/saveNote', { input: noteInput }));
  expect(note.review).toBeUndefined(); expect(note.history).toEqual([]);
  expect(value(await client.rpc<CardView>('studyforgePlugins/saveNote', { input: noteInput })).ref).toBe(note.ref);
  let graph = await trace(); const stage = graph.stages.find(s => !s.stage.pending)!;
  expect(stage.targets).toContainEqual({ ref: note.ref, version: 1, title: note.content.title });
  expect((await tool('read_thoughtmap', { stageId: stage.id })).text).toContain('图像斜率观察');
  expect((await tool('summarize_stage', { stageId: stage.id, basis: stage.stage.basis, expectedVersion: graph.version, title: '参数影响局部斜率', summary: '观察到斜率随参数改变；尚需说明变化规律。' })).failed).toBe(false);
  graph = await trace(); expect(graph.stages.find(s => s.id === stage.id)?.body).toContain('尚需说明');
  expect((await tool('summarize_stage', { stageId: stage.id, basis: stage.stage.basis, expectedVersion: 0, title: '过期覆盖', summary: '不该写入' })).failed).toBe(true);
  const savedVersion = graph.version;
  await runtime.restart(); client = await connectRuntime(runtime);
  expect((await read()).revision).toBe(2); expect((await trace()).version).toBe(savedVersion);
  expect((await trace()).stages.find(s => s.id === stage.id)?.targets[0]?.version).toBe(1);
  value(await client.rpc('studyforgePlugins/uninstallPackage', { input: { ref: plugin.ref, expectedVersion: plugin.revision } }));
  expect(value(await client.rpc<CardView>('studyforgeLearning/card', { input: { target: note.ref } })).content.title).toBe(note.content.title);
  expect((await trace()).stages.find(s => s.id === stage.id)?.body).toContain('尚需说明');
}, 90_000);
