import { expect, test } from 'vitest';
import { mkdtemp, readFile, writeFile, rm, stat, realpath } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import * as launches from '../../scripts/dev-isolated.ts';
import { connectVault } from '../fixtures/vault-http.ts';
import { relocateVaultRuntime } from '../../scripts/migrate-vault-runtime.ts';
import { liveVaultUrl } from '../../scripts/vault-launcher-state.ts';

test('persistent Vault keeps its origin, browser login, settings, files and classroom across process starts', async () => {
  expect('startVaultPersistent' in launches).toBe(true);
  const root = await mkdtemp(join(tmpdir(), 'notara-persistent-test-'));
  const migrated = root + '-stable';
  let runtime: launches.VaultRuntime | undefined;
  try {
    runtime = await launches.startVaultPersistent(root, { port: 0, testModel: true });
    const origin = new URL(runtime.authUrl).origin, oldUrl = runtime.authUrl;
    const login = await fetch(oldUrl, { redirect: 'manual' });
    expect(login.status).toBe(303);
    expect(await liveVaultUrl(root)).toBe(oldUrl);
    const cookie = login.headers.getSetCookie().map(item => item.split(';')[0]).join('; ');
    expect(cookie).not.toBe('');
    const settingsPath = join(root, 'home/settings.yaml');
    const settings = await readFile(settingsPath, 'utf8') + '\n# retained user settings\n';
    await writeFile(settingsPath, settings);
    await writeFile(join(root, 'workspace/vault/保留.md'), '# 保留资料\n');
    const client = await connectVault(runtime);
    const session = await client.createSession();
    await client.rename(session, '保留课堂');
    await client.close();
    await expect(launches.startVaultPersistent(root)).rejects.toThrow(/lock|locked|使用|运行/i);
    await runtime.stop(); runtime = undefined;
    expect(await liveVaultUrl(root)).toBeUndefined();
    expect(await stat(join(root, 'home/.credentials.yaml')).then(() => true)).toBe(true);
    runtime = await launches.startVaultPersistent(root);
    expect(new URL(runtime.authUrl).origin).toBe(origin);
    expect(runtime.authUrl).not.toBe(oldUrl);
    expect((await fetch(origin, { headers: { cookie } })).status).toBe(200);
    expect((await fetch(oldUrl, { redirect: 'manual' })).status).toBe(401);
    expect((await fetch(runtime.authUrl, { redirect: 'manual' })).status).toBe(303);
    expect(await readFile(settingsPath, 'utf8')).toBe(settings);
    expect(await readFile(join(root, 'workspace/vault/保留.md'), 'utf8')).toBe('# 保留资料\n');
    const resumed = await connectVault(runtime);
    expect((await resumed.sessions()).some(row => row.sessionId === session)).toBe(true);
    await resumed.close();
    expect((await stat(join(root, 'launcher.json'))).mode & 0o777).toBe(0o600);
    await runtime.stop(); runtime = undefined;
    await relocateVaultRuntime(root, migrated, Number(new URL(origin).port));
    expect(await realpath(root)).toBe(await realpath(migrated));
    runtime = await launches.startVaultPersistent(migrated);
    expect((await fetch(origin, { headers: { cookie } })).status).toBe(200);
    const moved = await connectVault(runtime);
    expect((await moved.sessions()).some(row => row.sessionId === session)).toBe(true);
    expect((await moved.ask(session, '继续课堂', { '继续课堂': '课堂已续接。' })).length).toBeGreaterThan(0);
    await moved.close();
    expect(await readFile(join(migrated, 'home/settings.yaml'), 'utf8')).toBe(settings);
    expect(await readFile(join(migrated, 'workspace/vault/保留.md'), 'utf8')).toBe('# 保留资料\n');
  } finally { await runtime?.stop(); for (const path of [root, migrated, root + '.pre-persistent']) await rm(path, { recursive: true, force: true }); }
}, 120_000);
