import { afterEach, expect, test } from 'vitest';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { PluginCandidate, PluginView, WorkbenchContent } from '@studyforge/contracts/plugins';
import type { CardView } from '@studyforge/contracts/cards';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
const value = <T>(reply: RemoteResult<T>): T => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };
test('native skill cache refreshes, workbenches pin versions and saved notes outlive uninstall', async () => {
  runtime = await startIsolated({ testModel: true }); const client = await connectRuntime(runtime);
  const open = () => client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}).then(value);
  const a = await open();
  const ask = async (text: string) => { value(await client.rpc('session/prompt', { request: { sessionId: a.sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text }] } })); await expect.poll(async () => (await readFile(join(runtime!.root, 'model-requests.jsonl'), 'utf8').catch(() => '')).includes(text)).toBe(true); await expect.poll(async () => value(await client.rpc<any>('session/list', { _request: {} })).items.find((row: any) => row.sessionId === a.sessionId)?.running).toBe(false); };
  await ask('/studyforge-semantic-search 先查当前资料');
  const source = join(runtime.root, 'plugin'); await mkdir(source);
  const manifest = { name: 'notara-workbench-test', version: '1.0.0', notara: { apiVersion: 1, title: '复盘', skills: [{ id: 'check', title: '插件追问', entry: 'skill.md' }], workbenches: [{ id: 'notes', title: '复盘工作台', entry: 'index.html', permissions: ['save-note'] }] } };
  const files = async (version: string, body: string) => { await writeFile(join(source, 'package.json'), JSON.stringify({ ...manifest, version })); await writeFile(join(source, 'skill.md'), 'PLUGIN_V1_TEXT：先等待学生自己说明理由。'); await writeFile(join(source, 'index.html'), '<main>' + body + '</main>'); };
  await files('1.0.0', '旧工作台');
  const prepare = () => client.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path: source } }).then(value);
  const first = await prepare(); await writeFile(join(source, 'index.html'), '<main>尚未发布的内容</main>');
  const install = (candidate: PluginCandidate, expectedVersion: number) => client.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: candidate.candidateId, expectedVersion, trustNative: false } }).then(value);
  let plugin = await install(first, 0);
  const skill = value(await client.rpc<{ id: string; title: string }[]>('studyforgeTeaching/tasks', {})).find(row => row.title === '插件追问')!;
  await ask('/' + skill.id + ' 检查我刚才的解释');
  expect(await readFile(join(runtime.root, 'model-requests.jsonl'), 'utf8')).toContain('PLUGIN_V1_TEXT');
  const trace = value(await client.rpc<any>('studyforgeTrace/read', { input: a }));
  const question = trace.nodes.filter((node: any) => node.kind === 'question').at(-1);
  expect(question.body).not.toContain(skill.id); expect(question.body).toContain('插件追问');
  const id = 'plugin-' + plugin.ref.slice(7) + '-notes';
  const old = value(await client.rpc<WorkbenchContent>('studyforgePlugins/openWorkbench', { input: { ...a, id } })); expect(old.html).toContain('旧工作台');
  await files('1.1.0', '新工作台'); plugin = await install(await prepare(), plugin.revision);
  expect(value(await client.rpc<WorkbenchContent>('studyforgePlugins/openWorkbench', { input: { ...a, id } })).html).toBe(old.html);
  const b = await open(); expect(value(await client.rpc<WorkbenchContent>('studyforgePlugins/openWorkbench', { input: { ...b, id } })).html).toContain('新工作台');
  const note = { ...a, id, digest: old.digest, operationId: 'same-note', note: { title: '复盘笔记', body: '我能独立说明定义域的作用。' } };
  const saved = value(await client.rpc<CardView>('studyforgePlugins/saveNote', { input: note }));
  expect(value(await client.rpc<CardView>('studyforgePlugins/saveNote', { input: note })).ref).toBe(saved.ref); expect(saved.review).toBeUndefined();
  plugin = value(await client.rpc<PluginView>('studyforgePlugins/setEnabled', { input: { ref: plugin.ref, expectedVersion: plugin.revision, enabled: false } }));
  expect((await client.rpc('studyforgePlugins/saveNote', { input: { ...note, operationId: 'after-disable' } })).ok).toBe(false);
  value(await client.rpc('studyforgePlugins/uninstallPackage', { input: { ref: plugin.ref, expectedVersion: plugin.revision } }));
  await runtime.restart(); const resumed = await connectRuntime(runtime);
  const cards = value(await resumed.rpc<CardView[]>('studyforgeLearning/cards', {})); expect(cards).toHaveLength(1); expect(cards[0]?.content.title).toBe('复盘笔记'); expect(cards[0]?.history).toEqual([]);
}, 90_000);

test('trusted native plugins load with Cordis and failed upgrades restore the current version', async () => {
  runtime = await startIsolated({ testModel: true }); const client = await connectRuntime(runtime);
  const source = join(runtime.root, 'native-plugin'), marker = join(runtime.root, 'native-marker.txt'); await mkdir(source);
  const files = async (version: string, fail = false) => {
    await writeFile(join(source, 'package.json'), JSON.stringify({ name: 'notara-native-test', version, type: 'module', main: 'index.js', notara: { apiVersion: 1, title: '原生测试' }, dsh: { bundle: { patch: './cordis.patch.yml' } } }));
    await writeFile(join(source, 'cordis.patch.yml'), JSON.stringify([{ insert: [{ id: 'notara-native-test', name: 'notara-native-test', config: { marker } }] }]));
    await writeFile(join(source, 'index.js'), "import { writeFileSync } from 'node:fs'; export function apply(ctx, config) { " + (fail ? "throw new Error('fixture load failure');" : "writeFileSync(config.marker, 'active');ctx.effect(() => () => writeFileSync(config.marker, 'stopped'));" ) + ' }');
  };
  await files('1.0.0');
  const prepare = () => client.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path: source } }).then(value);
  const first = await prepare(); expect(first.native).toBe(true);
  expect((await client.rpc('studyforgePlugins/installPackage', { input: { candidateId: first.candidateId, expectedVersion: 0, trustNative: false } })).ok).toBe(false);
  const install = (candidate: PluginCandidate, expectedVersion: number) => client.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: candidate.candidateId, expectedVersion, trustNative: true } });
  const installed = value(await install(first, 0)); if (installed.state !== 'enabled') throw new Error(runtime.log().replaceAll(runtime.authUrl, '[auth]').slice(-7000)); expect(await readFile(marker, 'utf8')).toBe('active');
  await files('1.1.0', true); expect((await install(await prepare(), installed.revision)).ok).toBe(false);
  expect(value(await client.rpc<PluginView[]>('studyforgePlugins/list', {}))[0]?.version).toBe('1.0.0'); expect(await readFile(marker, 'utf8')).toBe('active');
  const session = value(await client.rpc<{sessionId:string}>('studyforgeCreation/openTeacher', {}));
  value(await client.rpc('session/prompt', { request: { ...session, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '[slow] ' + '这是进行中的课堂。'.repeat(60) }] } }));
  await expect.poll(async () => value(await client.rpc<any>('session/list', { _request: {} })).items.find((row: any) => row.sessionId === session.sessionId)?.running).toBe(true);
  const pending = value(await client.rpc<PluginView>('studyforgePlugins/setEnabled', { input: { ref: installed.ref, expectedVersion: installed.revision, enabled: false } }));
  expect(pending.state).toBe('restart-required'); expect(await readFile(marker, 'utf8')).toBe('active');
  await runtime.restart(); const resumed = await connectRuntime(runtime);
  const restored = value(await resumed.rpc<PluginView[]>('studyforgePlugins/list', {}))[0]!;
  expect(restored.state).toBe('installed'); expect(await readFile(marker, 'utf8')).toBe('stopped');
  value(await resumed.rpc('studyforgePlugins/uninstallPackage', { input: { ref: restored.ref, expectedVersion: restored.revision } }));
  expect(await readFile(marker, 'utf8')).toBe('stopped');
  await files('1.2.0', true);
  const brokenCandidate = value(await resumed.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path: source } }));
  const broken = value(await resumed.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: brokenCandidate.candidateId, expectedVersion: 0, trustNative: true } }));
  expect(broken.state).toBe('failed'); expect(broken.issue).toBeTruthy();
  value(await resumed.rpc('studyforgePlugins/uninstallPackage', { input: { ref: broken.ref, expectedVersion: broken.revision } }));
}, 90_000);
