import { afterEach, expect, test } from 'vitest';
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { PluginCandidate, PluginView, WorkbenchContent, WorkbenchChoice, WorldbookView, WorldbookSelection, WorkbenchDraftView } from '@studyforge/contracts/plugins';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
const value = <T>(reply: RemoteResult<T>): T => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };

test('worldbook background is opt-in, editable, bounded and survives plugin removal; HTML drafts obey permissions and CAS', async () => {
  runtime = await startIsolated({ testModel: true }); let client = await connectRuntime(runtime);
  const install = async (path: string, expectedVersion = 0) => {
    const candidate = value(await client.rpc<PluginCandidate>('studyforgePlugins/prepare', { input: { kind: 'directory', path } }));
    return value(await client.rpc<PluginView>('studyforgePlugins/installPackage', { input: { candidateId: candidate.candidateId, expectedVersion, trustNative: false } }));
  };
  const fixturePackage = join(runtime.root, 'worldbook-fixture'); await cp(resolve('examples/plugins/worldbook'), fixturePackage, { recursive: true });
  const seed = JSON.parse(await readFile(resolve('tests/fixtures/classroom-seed.json'), 'utf8'));
  await writeFile(join(fixturePackage, 'worldbook.json'), JSON.stringify({ entries: seed.entries.slice(1) }));
  const seedManifest = JSON.parse(await readFile(join(fixturePackage, 'package.json'), 'utf8')); seedManifest.version = '1.0.0'; await writeFile(join(fixturePackage, 'package.json'), JSON.stringify(seedManifest));
  let plugin = await install(fixturePackage);
  const lab = await install(resolve('examples/plugins/function-lab'));
  const argument = await install(resolve('examples/plugins/argument-studio'));
  expect([plugin, lab, argument].every(row => row.state === 'enabled')).toBe(true);
  const session = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  const id = 'plugin-' + plugin.ref.slice(7) + '-worldbook', target = { ...session, id };
  expect(value(await client.rpc<WorkbenchContent>('studyforgePlugins/openWorkbench', { input: target })).kind).toBe('worldbook');
  let book = value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: target }));
  expect(book.enabled).toBe(false); expect(book.document.entries).toHaveLength(5);
  const requests = async () => (await readFile(join(runtime!.root, 'model-requests.jsonl'), 'utf8').catch(() => '')).trim().split('\n').filter(Boolean).map(line => JSON.parse(line) as { purpose: string; sessionId: string; messages: any[] }).filter(row => row.sessionId === session.sessionId && row.purpose !== 'session-title');
  const ask = async (text: string) => {
    const before = (await requests()).length;
    value(await client.rpc('session/prompt', { request: { ...session, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text }] } }));
    await expect.poll(async () => (await requests()).length).toBeGreaterThan(before);
    await expect.poll(async () => value(await client.rpc<any>('session/list', { _request: {} })).items.find((row: any) => row.sessionId === session.sessionId)?.running).toBe(false);
    return (await requests()).at(-1)!;
  };
  expect(JSON.stringify(await ask('讨论城邦水源。'))).not.toContain('旱季到来');
  book = value(await client.rpc<WorldbookView>('studyforgePlugins/useWorldbook', { input: { ...target, expectedVersion: 0, enabled: true } }));
  expect(JSON.stringify(await ask('看看城邦水源的约束。'))).toContain('旱季到来');
  const changed = { entries: [{ title: '自定义背景', content: 'WORLD_USER_EDIT_927：虚构实验数据', keywords: ['试验场'], enabled: true, always: false }] };
  const edit = { ...target, expectedVersion: 0, operationId: 'worldbook-first', document: changed };
  book = value(await client.rpc<WorldbookView>('studyforgePlugins/saveWorldbook', { input: edit }));
  expect(value(await client.rpc<WorldbookView>('studyforgePlugins/saveWorldbook', { input: edit })).revision).toBe(book.revision);
  expect((await client.rpc('studyforgePlugins/saveWorldbook', { input: { ...edit, operationId: 'stale' } })).ok).toBe(false);
  const matched = value(await client.rpc<WorldbookSelection>('studyforgePlugins/previewWorldbook', { input: { ...target, query: '试验场' } }));
  expect(matched.entries.map(x => x.title)).toEqual(['自定义背景']);
  expect(JSON.stringify(await ask('今天去试验场。'))).toContain('WORLD_USER_EDIT_927');
  // Bounded scan depth: the trigger word stays inside the recent-message window
  // (the last three completed user messages) for a few turns, then fades out.
  const stillWarm = await ask('现在讨论诗歌。');
  expect(JSON.stringify(stillWarm.messages.filter(row => row.role === 'user' && row.source?.kind === 'plugin').at(-1))).toContain('WORLD_USER_EDIT_927');
  await ask('再聊聊诗歌的韵脚。');
  await ask('然后看看散文。');
  const faded = await ask('最后谈点别的。');
  const lastContext = faded.messages.filter(row => row.role === 'user' && row.source?.kind === 'plugin').at(-1);
  expect(JSON.stringify(lastContext)).not.toContain('WORLD_USER_EDIT_927');
  // Other lessons share user-authored content, but do not inherit activation.
  const other = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  const otherBook = value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: { ...other, id } }));
  expect(otherBook.enabled).toBe(false); expect(otherBook.document).toEqual(changed);
  const labTarget = { ...session, id: 'plugin-' + lab.ref.slice(7) + '-lab', digest: lab.digest };
  expect(value(await client.rpc<WorkbenchDraftView>('studyforgePlugins/readDraft', { input: labTarget }))).toEqual({ revision: 0, json: 'null' });
  const draft = { ...labTarget, expectedVersion: 0, operationId: 'draft-one', json: JSON.stringify({ a: 2, observation: '顶点保持不变。' }) };
  const saved = value(await client.rpc<WorkbenchDraftView>('studyforgePlugins/saveDraft', { input: draft }));
  expect(value(await client.rpc<WorkbenchDraftView>('studyforgePlugins/saveDraft', { input: draft }))).toEqual(saved);
  expect((await client.rpc('studyforgePlugins/saveDraft', { input: { ...draft, operationId: 'stale-draft' } })).ok).toBe(false);
  expect((await client.rpc('studyforgePlugins/saveDraft', { input: { ...draft, digest: plugin.digest } })).ok).toBe(false);
  expect((await client.rpc('studyforgePlugins/readDraft', { input: { ...target, digest: plugin.digest } })).ok).toBe(false);
  expect((await client.rpc('studyforgePlugins/saveDraft', { input: { ...draft, json: '"' + 'a'.repeat(64_001) + '"' } })).ok).toBe(false);
  const source = join(runtime.root, 'updated-world'); await cp(fixturePackage, source, { recursive: true });
  const manifest = JSON.parse(await readFile(join(source, 'package.json'), 'utf8')); manifest.version = '1.1.0'; manifest.notara.worldbooks[0].id = 'worldbook-v2'; await writeFile(join(source, 'package.json'), JSON.stringify(manifest));
  await writeFile(join(source, 'worldbook.json'), JSON.stringify({ entries: [] })); plugin = await install(source, plugin.revision);
  expect(value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: target })).document).toEqual(changed);
  expect(value(await client.rpc<WorkbenchChoice[]>('studyforgePlugins/workbenches', { input: session })).some(row => row.id === id)).toBe(true);
  const fresh = value(await client.rpc<{ sessionId: string }>('studyforgeCreation/openTeacher', {}));
  expect(value(await client.rpc<WorkbenchChoice[]>('studyforgePlugins/workbenches', { input: fresh })).some(row => row.id === id)).toBe(false);
  plugin = value(await client.rpc<PluginView>('studyforgePlugins/setEnabled', { input: { ref: plugin.ref, expectedVersion: plugin.revision, enabled: false } }));
  const disabled = await ask('试验场现在停用了。');
  expect(JSON.stringify(disabled.messages.filter(row => row.role === 'user' && row.source?.kind === 'plugin').at(-1))).not.toContain('WORLD_USER_EDIT_927');
  value(await client.rpc('studyforgePlugins/uninstallPackage', { input: { ref: plugin.ref, expectedVersion: plugin.revision } }));
  expect((await client.rpc('studyforgePlugins/readWorldbook', { input: target })).ok).toBe(false);
  await runtime.restart(); client = await connectRuntime(runtime);
  expect(value(await client.rpc<WorkbenchDraftView>('studyforgePlugins/readDraft', { input: labTarget }))).toEqual(saved);
  await install(source);
  expect(value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: target })).document).toEqual(changed);
  // A malformed worldbook is rejected during prepare, before replacing an installed package.
  await writeFile(join(source, 'worldbook.json'), JSON.stringify({ entries: [{ title: '缺内容' }] }));
  expect((await client.rpc('studyforgePlugins/prepare', { input: { kind: 'directory', path: source } })).ok).toBe(false);
  expect(value(await client.rpc<WorldbookView>('studyforgePlugins/readWorldbook', { input: target })).document).toEqual(changed);
}, 120_000);
