import { afterEach, expect, test } from 'vitest';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { SessionCreateValue, SessionListValue } from '@deepseek-ai/dsh-api-session-controller';
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol';
import type { CourseView } from '@studyforge/contracts/courses';
import type { SetView } from '@studyforge/contracts/sets';
import { startIsolated, type IsolatedRuntime } from '../../scripts/dev-isolated.ts';
import { connectRuntime } from '../fixtures/http-runtime.ts';
let runtime: IsolatedRuntime | undefined;
afterEach(async () => { await runtime?.stop(); });
const value = <T>(reply: RemoteResult<T>): T => { if (!reply.ok) throw new Error(JSON.stringify(reply.error)); return reply.value; };

test('lesson subjects inherit the set, override independently, clear and restore without changing pedagogy or another lesson', async () => {
  runtime = await startIsolated({ testModel: true });
  let client = await connectRuntime(runtime);
  const set = value(await client.rpc<SetView>('studyforgeOrganization/createSet', { input: { operationId: 'subjects-set', set: { name: '跨科练习', subjects: ['数学'] } } }));
  const create = async () => value(await client.rpc<SessionCreateValue>('session/create', { request: { cwd: join(runtime!.root, 'classroom'), agentPreset: 'studyforge-learning' } })).sessionId;
  const a = await create(), b = await create();
  for (const sessionId of [a, b]) value(await client.rpc('studyforgeCourses/update', { input: { sessionId, operationId: 'select-set-'+sessionId, expectedVersion: 0, patch: { learningSetRef: set.ref } } }));
  const subjects = async (sessionId: string) => value(await client.rpc<{ effective: string[]; inherited: boolean }>('studyforgeTeaching/subjects', { input: { sessionId } }));
  expect(await subjects(a)).toMatchObject({ effective: ['数学'], inherited: true });
  let row = value(await client.rpc<CourseView>('studyforgeCourses/read', { input: { sessionId: a } }));
  row = value(await client.rpc<CourseView>('studyforgeCourses/update', { input: { sessionId: a, operationId: 'physics', expectedVersion: row.version, patch: { subjects: ['物理'], teachingRef: 'feynman', guided: true } } }));
  expect(await subjects(a)).toMatchObject({ effective: ['物理'], inherited: false });
  expect(await subjects(b)).toMatchObject({ effective: ['数学'], inherited: true });
  value(await client.rpc('session/prompt', { request: { sessionId: a, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: '按这节课的科目开始' }] } }));
  await expect.poll(async () => value(await client.rpc<SessionListValue>('session/list', { _request: {} })).items.find(item => item.sessionId === a)?.running).toBe(false);
  const requests = await readFile(join(runtime.root, 'model-requests.jsonl'), 'utf8');
  expect(requests).toContain('本课涉及科目：物理'); expect(requests).toContain('# 费曼法');
  row = value(await client.rpc<CourseView>('studyforgeCourses/update', { input: { sessionId: a, operationId: 'general', expectedVersion: row.version, patch: { subjects: [] } } }));
  expect(await subjects(a)).toMatchObject({ effective: [], inherited: false });
  row = value(await client.rpc<CourseView>('studyforgeCourses/update', { input: { sessionId: a, operationId: 'inherit', expectedVersion: row.version, patch: { subjects: null } } }));
  expect(await subjects(a)).toMatchObject({ effective: ['数学'], inherited: true });
  expect(row.data).toMatchObject({ teachingRef: 'feynman', guided: true, learningSetRef: set.ref });
  await runtime.restart(); client = await connectRuntime(runtime);
  expect(await subjects(a)).toMatchObject({ effective: ['数学'], inherited: true });
  expect(value(await client.rpc<SetView>('studyforgeOrganization/set', { input: { ref: set.ref } })).subjects).toEqual(['数学']);
}, 45_000);
