import {$,N,shell,click,math,sourceButtons,workingDocument,status,ask,note,value,textButton} from './common.ts';
shell('老师黑板','课堂推导、图示与关键结论。','<div class="actions"><button id="add">＋ 添加板书</button><button id="save" class="primary">保存修改</button><button id="reload">读取最新</button></div><section id="blocks"></section><div class="actions"><button id="teacher">请老师整理黑板</button><button id="note">保存整块黑板为笔记</button></div>');
let selected=-1;const doc=await workingDocument('blackboard',render);
function render(){const root=$('blocks');root.replaceChildren();if(!doc.data.blocks.length){root.textContent='还没有板书。可以添加一段，或请老师整理。';return;}
 doc.data.blocks.forEach((block,index)=>{const section=document.createElement('section');section.className='section';const h=document.createElement('h2');h.textContent=block.title;section.append(h);const body=document.createElement('div');math(body,block.body);section.append(body);
 if(block.diagram){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 500 250');svg.classList.add('plot');for(const edge of block.diagram.edges){const a=block.diagram.nodes[edge.from]!,b=block.diagram.nodes[edge.to]!,line=document.createElementNS(svg.namespaceURI,'line');for(const [k,v] of Object.entries({x1:a.x*4.5+25,y1:a.y*2+25,x2:b.x*4.5+25,y2:b.y*2+25,stroke:'var(--notara-muted)'}))line.setAttribute(k,String(v));svg.append(line);}for(const node of block.diagram.nodes){const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',String(node.x*4.5+25));label.setAttribute('y',String(node.y*2+25));label.setAttribute('text-anchor','middle');label.textContent=node.label;svg.append(label);}section.append(svg);}
 const actions=document.createElement('div');actions.className='actions';actions.append(textButton('编辑',()=>{selected=index;render();}),textButton('追问这一块',()=>{void ask(`关于黑板「${block.title}」：\n${block.body}\n我想进一步讨论：`).catch(e=>status(e.message));}),textButton('存为笔记',()=>note(block.title,block.body)));sourceButtons(actions,block.links,selected===index?()=>{doc.changed();render();}:undefined);section.append(actions);
 if(selected===index){const title=document.createElement('input');title.setAttribute('aria-label','板书标题');title.value=block.title;title.oninput=()=>{block.title=title.value;doc.changed();};const input=document.createElement('textarea');input.setAttribute('aria-label','板书正文');input.value=block.body;input.oninput=()=>{block.body=input.value;doc.changed();};section.append(title,input,textButton('关联资料',()=>{void N.pickSource().then(link=>{block.links.push(link);doc.changed();render();}).catch(e=>status(e.message));}),textButton('完成编辑',()=>{selected=-1;render();}),textButton('移除板书',()=>{doc.data.blocks.splice(index,1);selected=-1;doc.changed();render();}));}root.append(section);});}
click('add',()=>{doc.data.blocks.push({title:'新板书',body:'',links:[]});selected=doc.data.blocks.length-1;doc.changed();render();});click('save',()=>doc.save());click('reload',()=>doc.reload());click('teacher',()=>ask('请使用read_workbench读取「老师黑板」，把本课讲解的关键公式、推导和图示通过update_workbench整理到黑板，保留已有内容。'));click('note',()=>note(doc.data.title,doc.data.blocks.map(b=>'## '+b.title+'\n\n'+b.body).join('\n\n')));render();
