export const catalog = [
 {name:'blackboard',title:'老师黑板',description:'边讲边整理公式、图示和推导，选择一块继续追问。',skill:'整理课堂黑板',permissions:['document','sources','compose','save-note'],seed:{kind:'blackboard',title:'课堂黑板',blocks:[{title:'示例：平方展开',body:'$$(a+b)^2=a^2+2ab+b^2$$\n\n为什么中间项是 $2ab$？可以把面积分成四块来解释。',links:[]},{title:'示例：讨论的路径',body:'从观察到表达，每一步都可以留下问题。',links:[],diagram:{nodes:[{label:'观察',x:10,y:50},{label:'猜想',x:35,y:50},{label:'检验',x:65,y:50},{label:'表达',x:90,y:50}],edges:[{from:0,to:1},{from:1,to:2},{from:2,to:3}]}}]},instructions:'讲解过程中通过read_workbench定位老师黑板，再按读到的revision和document schema使用update_workbench。保留已有推导，只修改当下讲清的段落。公式用$或$$；图示用diagram节点坐标和边的数组下标，边必须有真实节点。不要把展示过的结论记成学生已掌握。工作文档可以直接共编，存为正式笔记仍由学生确认。'},
 {name:'error-clinic',title:'错解诊所',description:'找出第一处错误，解释原因，再修复解答。',skill:'准备错解练习',permissions:['document','sources','compose','draft','save-note'],seed:{kind:'clinic',title:'示例：开平方丢掉了什么？',question:'求方程 $x^2=9$ 的全部实数解。以下解答故意含错。',steps:['原方程为 $x^2=9$。','两边开平方，得到 $x=\\sqrt{9}=3$。','所以方程只有一个实数解 $x=3$。'],errorIndex:1,explanation:'第二步把 $\\sqrt{x^2}$ 写成了 $x$，忽略了 $\\sqrt{x^2}=|x|$。第一处错误在这里。',repair:'由 $|x|=3$ 得 $x=3$ 或 $x=-3$，代入两者都满足原方程。',links:[]},instructions:'先确定一个真实知识点，独立验算正确解，再构造一处有教学价值的错误及其后续传播。读取错解诊所的document后修改question、steps、0-based errorIndex、explanation与repair。第一处错误必须与索引对应，先完整校验再update_workbench；界面在学生选步并写理由后才展示参考解析。老师评理由，不把选对位置当掌握。可换题，不把错误练习当真实史料或学生旧错题。'},
 {name:'geometry-lab',title:'几何作图台',description:'拖点观察三角形与圆周角，检验几何猜想。',skill:'开展几何实验',permissions:['compose','draft','save-note'],instructions:'学生可在几何作图台拖动A/B/C，选择三角形内角/重心或圆周角。你看不到未发送的操作，只依据学生发来的测量与猜想讨论。让学生固定必要条件、只改一个点，主动检查共线、重合和跨弧；同弧圆周角不变不等于跨弧也不变。数值现象不是证明；观察后请学生说明理由。不要虚构图像操作已执行。'},
 {name:'evidence-detective',title:'史料侦探局',description:'对照材料、分类证据，建立可追溯的判断。',skill:'准备史料调查',permissions:['document','sources','compose','save-note'],seed:{kind:'evidence',title:'示例：河港停航的原因',fictional:true,question:'【虚构练习】河港为什么停航？三份材料能支持哪些判断？',entries:[{title:'码头值班记录',body:'五月七日上午，水位标尺低于通航警戒线，港口暂停放行。',category:'unclassified',reason:'',links:[]},{title:'商人的信',body:'我听船夫说，这次停航可能是上游闸门出了故障。',category:'unclassified',reason:'',links:[]},{title:'后来的分析',body:'如果闸门故障导致水位下降，那么停航可能与闸门有关；但尚缺闸门检修记录。',category:'unclassified',reason:'',links:[]}],conclusion:''},instructions:'从用户指定的原文、卡片和课堂中检索真正涉及主题的材料，读原文后才摘录。把真实来源绑定到entries.links，不编造引文、年代或页码。根据schema更新史料侦探局，真实材料fictional=false；没有真实材料时仅可明确标为虚构练习。区分直接记录、转述、推断，要求说明每份材料支持什么、不能支持什么以及相互冲突。保留学生已写的证据判断和结论。'},
 {name:'time-atlas',title:'时空地图',description:'把事件连到时间、地点、原文与课堂。',skill:'整理时空线索',permissions:['document','sources','compose','save-note'],seed:{kind:'atlas',title:'示例：一位旅行者的记录',fictional:true,events:[{title:'出发',year:1900,place:'杭州（演示地点）',latitude:30.25,longitude:120.15,body:'虚构旅行情境，用于示范事件定位；不是历史人物行程。',links:[]},{title:'抵达',year:1901,place:'南京（演示地点）',latitude:32.06,longitude:118.8,body:'在时间轴选择事件，可以定位地图并关联资料。',links:[]}]},instructions:'提取原文中有根据的事件、年代与地点，读后用read_workbench/update_workbench维护时空地图。year使用整数，公元前填负数；经纬度表示地点近似位置，不能冒充历史疆域。没有确定年份或地点的事件先说明缺口，不猜精确值来填满地图。真实事件fictional=false，并绑定具体来源link；已有笔记和用户关系须保留。'},
 {name:'seminar-room',title:'多智能体研讨室',description:'邀请同伴、质疑者和助教独立讨论，支持点名追问。',skill:'主持独立研讨',permissions:['seminar','compose','draft','save-note'],instructions:'学生在研讨室选择真实独立发言者并给出材料。你主持讨论：准确呈现各方意见，保留分歧，核查最影响结论的事实。只有真实运行结果才称为独立意见，不用自己写多角色文案冒充。助教必须收到既有参考标准，同伴和质疑者不收到这份标准；所有人都不自动接收学生学情。学生可以追问同一个子会话，汇总需实际阅读发言内容；失败或中断不当完成。'},
 {name:'scenario-simulator',title:'情境模拟器',description:'结合世界书做出多轮决策，观察并复盘后果。',skill:'设计情境模拟',permissions:['document','compose','worldbook-context','draft','save-note'],seed:{kind:'simulation',title:'城邦水源与粮食',background:'【虚构教学模拟】澄湾面临五轮旱季决策。每轮把自然补给与政策影响合并成下列固定数值，供讨论权衡，不用于现实预测。',rounds:5,resources:[{title:'蓄水',initial:70,minimum:20,maximum:100},{title:'粮食',initial:50,minimum:25,maximum:100},{title:'生态',initial:60,minimum:30,maximum:100}],choices:[{title:'扩大灌溉',description:'以蓄水与生态换取粮食。',effects:[-15,20,-8]},{title:'节水休耕',description:'减少粮食供给，恢复蓄水与生态。',effects:[10,-12,12]},{title:'温和配给',description:'以较小幅度同时消耗资源。',effects:[-5,2,-2]}]},instructions:'先读已启用世界书和情境模拟器的当前工作文档，提炼一组虚构但可检查的资源、约束、选择和数值后果。effects数组顺序与resources一致，初始值必须在minimum/maximum之间。通过update_workbench发布规则，课堂明确解释简化假设，不拿固定数值模拟充当现实预测。运行中规则改变需要学生重新开始；不静默修改已经作出的决策记录。复盘学生明说的理由、目标与代价，不把游戏通关当掌握。'},
] as const;
