import {$,N,shell,click,status,value,note,ask,draftControls} from './common.ts';
import {angle,triangle,onCircle,type Point} from './geometry-model.ts';
shell('几何作图台','拖动顶点，观察哪些量改变、哪些量保持。','<label>实验<select id="mode"><option value="triangle">三角形内角与重心</option><option value="circle">圆周角</option></select></label><svg id="plot" class="plot" viewBox="0 0 480 360" role="img" aria-label="可拖动的几何图"></svg><p id="measure"></p><small>顶点可拖动，也可聚焦后用方向键移动。测量不代替证明。</small><label>我的猜想<textarea id="guess"></textarea></label><label>验证与疑问<textarea id="observation"></textarea></label><div class="actions"><button id="reset">重置图形</button><button id="draft">保存草稿</button><button id="ask">交给老师讨论</button><button id="note">整理为笔记</button></div>');
let mode='triangle',points:Point[]=[{x:90,y:270},{x:390,y:270},{x:270,y:70}];const svg=$<SVGSVGElement & HTMLElement>('plot'),ns='http://www.w3.org/2000/svg';
function el(tag:string,attrs:Record<string,string|number>){const e=document.createElementNS(ns,tag);for(const [key,v]of Object.entries(attrs))e.setAttribute(key,String(v));return e;}
function measurement(){const t=triangle(points);if(t.area<1)return '三个点接近共线，请调整顶点。';return mode==='triangle'?'内角：'+t.angles.map(n=>n.toFixed(1)+'°').join(' · ')+'；合计 '+t.angles.reduce((a,b)=>a+b,0).toFixed(1)+'°':'圆周角 ∠ACB = '+angle(points[0]!,points[2]!,points[1]!).toFixed(1)+'°；保持A、B，拖动C观察。';}
function draw(){svg.replaceChildren();if(mode==='circle')svg.append(el('circle',{cx:240,cy:180,r:140,fill:'none',stroke:'var(--notara-border)'}));svg.append(el('polygon',{points:points.map(p=>p.x+','+p.y).join(' '),fill:'color-mix(in srgb,var(--notara-accent) 6%,transparent)',stroke:'var(--notara-accent)','stroke-width':1.7}));if(mode==='triangle'){const c=triangle(points).centroid;for(const p of points)svg.append(el('line',{x1:p.x,y1:p.y,x2:c.x,y2:c.y,stroke:'var(--notara-muted)','stroke-dasharray':'4 4'}));svg.append(el('circle',{cx:c.x,cy:c.y,r:3,fill:'var(--notara-muted)'}));}
 points.forEach((p,i)=>{const dot=el('circle',{cx:p.x,cy:p.y,r:9,fill:'var(--notara-accent)',tabindex:0,role:'button','aria-label':'顶点 '+String.fromCharCode(65+i)});dot.addEventListener('pointerdown',event=>{const e=event as PointerEvent;svg.setPointerCapture(e.pointerId);drag=i;});dot.addEventListener('keydown',event=>{const e=event as KeyboardEvent;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();move(i,{x:p.x+(e.key==='ArrowRight'?3:e.key==='ArrowLeft'?-3:0),y:p.y+(e.key==='ArrowDown'?3:e.key==='ArrowUp'?-3:0)});(svg.querySelectorAll('[role=button]')[i] as SVGElement)?.focus();});const label=el('text',{x:p.x+13,y:p.y-10});label.textContent=String.fromCharCode(65+i);svg.append(dot,label);});$('measure').textContent=measurement();}
function move(i:number,p:Point){points[i]=mode==='circle'?onCircle(p):{x:Math.max(15,Math.min(465,p.x)),y:Math.max(15,Math.min(345,p.y))};draw();status('有未保存的实验');}let drag=-1;
svg.addEventListener('pointermove',e=>{if(drag<0)return;const r=svg.getBoundingClientRect();move(drag,{x:(e.clientX-r.left)/r.width*480,y:(e.clientY-r.top)/r.height*360});});svg.addEventListener('pointerup',()=>{drag=-1;});svg.addEventListener('pointercancel',()=>{drag=-1;});
function reset(){points=mode==='triangle'?[{x:90,y:270},{x:390,y:270},{x:270,y:70}]:[onCircle({x:380,y:180}),onCircle({x:140,y:80}),onCircle({x:170,y:310})];draw();}
$('mode').onchange=()=>{mode=value('mode');reset();};click('reset',reset);const summary=()=>`${mode==='triangle'?'三角形':'圆周角'}实验\n${measurement()}\n猜想：${value('guess')}\n验证与疑问：${value('observation')}`;click('ask',()=>ask('请讨论我的几何猜想，区分测量现象和证明。\n'+summary()));click('note',()=>note('几何实验',summary()));await draftControls(()=>({mode,points,guess:value('guess'),observation:value('observation')}),d=>{if(['triangle','circle'].includes(d.mode)&&Array.isArray(d.points)&&d.points.length===3&&d.points.every((p:Point)=>Number.isFinite(p.x)&&Number.isFinite(p.y))){mode=d.mode;points=d.points;$<HTMLSelectElement>('mode').value=mode;$<HTMLTextAreaElement>('guess').value=d.guess??'';$<HTMLTextAreaElement>('observation').value=d.observation??'';}});draw();
