import {$,N,shell,click,status,workingDocument,value,note,ask,textButton,draftControls} from './common.ts';
import {advance} from './simulation-model.ts';
shell('情境模拟器','每次决策，都留下可检查的后果。','<p class="tag">虚构教学模拟 · 规则公开</p><h2 id="title"></h2><p id="background"></p><details><summary>本课世界书背景</summary><button id="worldbook">读取已启用的背景</button><pre id="world"></pre></details><p id="round"></p><section id="resources" class="fields"></section><details><summary>查看规则与效果</summary><div id="rules"></div></details><section id="choices" class="actions"></section><label>我的决策理由<textarea id="reason"></textarea></label><section id="history" class="section"></section><div class="actions"><button id="draft">保存模拟进度</button><button id="reset">重新开始</button><button id="ask">请老师复盘决策</button><button id="generate">从世界书设计新情境</button><button id="note">整理为笔记</button></div>');
let resources:number[]=[],logs:{choice:string;reason:string;values:number[];viable:boolean;clipped:boolean}[]=[],basis=0;const doc=await workingDocument('simulation',()=>{if(logs.length){status('模拟规则有更新；当前进度需重新开始后使用。');return;}start();});
let config=structuredClone(doc.data);
function start(){config=structuredClone(doc.data);resources=config.resources.map(r=>r.initial);logs=[];basis=doc.revision;render();}
function render(){$('title').textContent=config.title;$('background').textContent=config.background;$('round').textContent=`第 ${Math.min(logs.length+1,config.rounds)} / ${config.rounds} 轮${logs.length>=config.rounds?' · 已结束':''}`;$('resources').replaceChildren();config.resources.forEach((r,i)=>{const box=document.createElement('div');box.className='section';box.textContent=`${r.title}：${resources[i]}（最低 ${r.minimum}）`;$('resources').append(box);});$('rules').textContent=config.choices.map(c=>c.title+'：'+c.effects.map((v,i)=>`${config.resources[i]!.title} ${v>=0?'+':''}${v}`).join('，')).join('\n');$('choices').replaceChildren();config.choices.forEach(c=>{const b=textButton(c.title,()=>{if(basis!==doc.revision){status('规则已变化，请先重新开始。');return;}if(!value('reason').trim()){status('先写下这次选择的理由。');return;}const result=advance(resources,c.effects,config.resources);resources=result.values;logs.push({choice:c.title,reason:value('reason'),...result});$<HTMLTextAreaElement>('reason').value='';render();status(result.viable?'这轮仍满足所有最低约束。':'有资源低于最低约束，请检查代价。');});b.title=c.description;b.disabled=logs.length>=config.rounds||basis!==doc.revision;$('choices').append(b);});$('history').replaceChildren();logs.forEach((log,i)=>{const p=document.createElement('p');p.textContent=`${i+1}. ${log.choice} → ${log.values.join(' / ')}${log.clipped?'（按0与上限截取）':''}\n理由：${log.reason}`;$('history').append(p);});}
const summary=()=>`【虚构模拟】${config.title}\n${config.background}\n`+logs.map((l,i)=>`${i+1}. ${l.choice}；理由：${l.reason}；结果：${l.values.map((v,k)=>config.resources[k]!.title+'='+v).join('，')}`).join('\n');
click('worldbook',async()=>{const result=await N.worldbook(config.title+' '+config.background);$('world').textContent=result.text||'本课没有启用或命中的世界书条目。';});click('reset',()=>{if(logs.length&&!confirm('重新开始当前模拟？已保存笔记不受影响。'))return;start();});click('ask',()=>ask('请根据公开规则复盘我的选择，区分目标、约束和代价。\n'+summary()));click('generate',()=>ask('请结合本课已启用世界书，读取「情境模拟器」工作文档，设计一组明确标为虚构的资源、选择和数值效果，用update_workbench保存。规则必须可检查，不代替现实预测。'));click('note',()=>note(config.title+' · 决策复盘',summary()));start();await draftControls(()=>({basis,resources,logs,config}),d=>{if(d.config?.kind==='simulation'&&Array.isArray(d.config.resources)&&Array.isArray(d.resources)&&d.resources.length===d.config.resources.length&&d.resources.every(Number.isFinite)&&Array.isArray(d.logs)){basis=d.basis;config=d.config;resources=d.resources;logs=d.logs;render();}else status('保存的进度属于旧规则，请重新开始。');});
