import {$,N,shell,click,sourceButtons,workingDocument,status,ask,note,value,textButton} from './common.ts';
import land from './world-land.json';
shell('时空地图','在时间与地点之间连接材料。','<p id="fiction" class="tag"></p><svg id="map" class="plot" viewBox="0 0 360 180" role="img" aria-label="事件地图"></svg><div class="actions"><button id="zoom-in">放大地图</button><button id="zoom-out">缩小地图</button><button id="reset">全图</button></div><small>底图：Natural Earth，自然陆地轮廓，不表示历史疆界。</small><section id="timeline" class="section"></section><section id="editor"></section><div class="actions"><button id="add">＋ 添加事件</button><button id="save" class="primary">保存修改</button><button id="reload">读取最新</button></div><div class="actions"><button id="generate">从资料整理时空线索</button><button id="note">整理为笔记</button></div>');
const ns='http://www.w3.org/2000/svg';let selected=-1,zoom=1;const doc=await workingDocument('atlas',render);
function node(tag:string,attrs:Record<string,string|number>){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e;}
function render(){const map=$('map');map.replaceChildren();const active=doc.data.events[selected];const w=360/zoom,h=180/zoom,cx=active?active.longitude+180:180,cy=active?90-active.latitude:90;map.setAttribute('viewBox',`${Math.max(0,Math.min(360-w,cx-w/2))} ${Math.max(0,Math.min(180-h,cy-h/2))} ${w} ${h}`);map.append(node('path',{d:land.path,fill:'color-mix(in srgb,var(--notara-muted) 16%,var(--notara-surface))',stroke:'var(--notara-border)','stroke-width':.2}));for(let lon=0;lon<=360;lon+=30)map.append(node('line',{x1:lon,x2:lon,y1:0,y2:180,stroke:'var(--notara-border)','stroke-width':.15}));for(let lat=0;lat<=180;lat+=30)map.append(node('line',{x1:0,x2:360,y1:lat,y2:lat,stroke:'var(--notara-border)','stroke-width':.15}));
 doc.data.events.forEach((e,index)=>{const g=node('g',{role:'button',tabindex:0,'aria-label':e.title}),dot=node('circle',{cx:e.longitude+180,cy:90-e.latitude,r:(selected===index?3:2)/Math.sqrt(zoom),fill:'var(--notara-accent)'});g.append(dot);g.addEventListener('click',()=>{selected=index;render();});g.addEventListener('keydown',ev=>{if((ev as KeyboardEvent).key==='Enter'){selected=index;render();}});map.append(g);});$('fiction').textContent=doc.data.fictional?'演示事件 · 虚构':'事件来自资料，坐标为地点近似位置';
 $('timeline').replaceChildren();[...doc.data.events.entries()].sort((a,b)=>a[1].year-b[1].year).forEach(([index,e])=>{const b=textButton(`${e.year<0?'公元前'+Math.abs(e.year):e.year}年 · ${e.title} · ${e.place}`,()=>{selected=index;render();});b.className='step';b.setAttribute('aria-pressed',String(index===selected));$('timeline').append(b);});
 const editor=$('editor');editor.replaceChildren();if(!active)return;
 for(const [key,label,type]of [['title','事件标题','text'],['year','年份（公元前填负数）','number'],['place','地点','text'],['latitude','纬度','number'],['longitude','经度','number']] as const){const l=document.createElement('label'),input=document.createElement('input');l.textContent=label;input.type=type;input.value=String(active[key]);input.onchange=()=>{Object.assign(active,{[key]:type==='number'?Number(input.value):input.value});doc.changed();};l.append(input);editor.append(l);}const body=document.createElement('textarea');body.setAttribute('aria-label','事件说明');body.value=active.body;body.oninput=()=>{active.body=body.value;doc.changed();};editor.append(body);sourceButtons(editor,active.links,()=>{doc.changed();render();});editor.append(textButton('关联出处',()=>{void N.pickSource().then(link=>{active.links.push(link);doc.changed();render();}).catch(e=>status(e.message));}),textButton('更新图上位置',render),textButton('删除事件',()=>{doc.data.events.splice(selected,1);selected=-1;doc.changed();render();}));}
click('zoom-in',()=>{zoom=Math.min(8,zoom*2);render();});click('zoom-out',()=>{zoom=Math.max(1,zoom/2);render();});click('reset',()=>{zoom=1;render();});click('add',()=>{doc.data.events.push({title:'新事件',year:2000,place:'',latitude:0,longitude:0,body:'',links:[]});selected=doc.data.events.length-1;doc.changed();render();});click('save',()=>doc.save());click('reload',()=>doc.reload());click('generate',()=>ask('请从当前资料中核对事件、年代与地点，使用read_workbench和update_workbench填入「时空地图」并关联原文/卡片/课堂。未确定年代地点不要假装精确。'));click('note',()=>note(doc.data.title,(doc.data.fictional?'【虚构演示】\n':'')+doc.data.events.map(e=>`${e.year}年 · ${e.title} · ${e.place}\n${e.body}\n来源：${e.links.map(l=>l.title).join('、')||'未关联'}`).join('\n\n')));render();
