import css from './board-client.css';
import { createVaultClient } from './remote-client.js';
import { VIEW_IDS } from './views-client.js';
import { renderBoardMarkdown,highlightBoardText,HIGHLIGHTS,exportBoard,boardImageTargets,stableBoardPreview } from './board-render.js';
import { getBoardStream,subscribeBoardStream } from './board-stream.js';
import { createMathInteractive } from './interactive-math-client.js';

const EMPTY={revision:null,blocks:[],sources:[],edges:[]};
const unwrap=result=>{if(!result?.ok)throw new Error(result?.error?.message??'白板暂时无法读取，请稍后重试。');return result.value;};
const colorNames={blue:'蓝色',green:'绿色',orange:'橙色',pink:'粉色'};
export function createLessonBoard(React) {
  const h=React.createElement,{useState,useRef,useEffect,useMemo}=React;
  const MathInteractive=props=>createMathInteractive(React,props);
  function Block({block,source,stream,onDrag,onSource,onReturn,onSelection,assetUrls,onInteractionChange,onExpand,onDiscuss}) {
    const inner=h('div',{className:'nb-body',onMouseUp:e=>onSelection(e,block,source),onClick:e=>{const link=e.target.closest('[data-source]');if(link){e.preventDefault();onSource(link.dataset.source);}},dangerouslySetInnerHTML:{__html:renderBoardMarkdown(stream?stableBoardPreview(block.body):block.body,{assetUrls})}});
    const interactive=block.interactive?.provider==='math'&&block.interactiveScene
      ? h(MathInteractive,{scene:block.interactiveScene,onChange:patch=>onInteractionChange(block,patch),onExpand:()=>onExpand(block),onDiscuss})
      : block.interactiveState==='unavailable'?h('div',{className:'nb-interactive-unavailable'},'互动图暂时不可用，板书文字仍然保留。'):null;
    return h('article',{className:'nb-block','data-block-id':block.id??block.path,'data-stream':stream?'true':undefined,style:{left:block.x,top:block.y,width:block.width}},
      h('div',{className:'nb-block-tools'},h('button',{className:'nb-grip','aria-label':'移动 '+block.title,onPointerDown:e=>onDrag(e,block,source)},'⠿ 拖动'),source&&block.missing?h('span',null,'资料已移动或不可用'):null),
      stream&&h('div',{className:'nb-live-label'},stream==='streaming'?'正在板书…':'等待保存…'),
      block.kind&&block.kind!=='note'?h('details',null,h('summary',null,block.title),inner,interactive):h(React.Fragment,null,h('h2',null,block.title),inner,interactive),
      source&&h('div',{className:'nb-source-actions'},h('button',{disabled:block.missing,onClick:()=>onSource(block.path)},'打开资料'),...block.usedBy.map((id,index)=>h('button',{key:id,onClick:()=>onReturn(id)},block.usedBy.length===1?'回到板书':'引用位置 '+(index+1)))));
  }
  return function Board({ctx,sessionId,visible,openView,onDiscuss}) {
    const client=useMemo(()=>createVaultClient(ctx,sessionId),[ctx,sessionId]);
    const [board,setBoard]=useState(EMPTY),[face,setFace]=useState('board'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[stream,setStream]=useState(()=>getBoardStream(sessionId)),[expandedInteraction,setExpandedInteraction]=useState(null);
    const [camera,setCamera]=useState({board:{x:0,y:0,z:1},sources:{x:0,y:0,z:1}}),[follow,setFollow]=useState(true),[exporting,setExporting]=useState(false),[include,setInclude]=useState({});
    const [assetUrls,setAssetUrls]=useState({}),imagePaths=boardImageTargets(board.blocks.map(b=>b.body).join('\n')).join('\n');
    useEffect(()=>{let alive=true;for(const path of imagePaths.split('\n').filter(Boolean))if(!assetUrls[path])client.readAsset({path}).then(unwrap).then(asset=>{if(alive&&/^image\/(?:png|jpeg|gif|webp|svg\+xml)$/.test(asset.mime))setAssetUrls(prev=>({...prev,[path]:asset.dataUrl}));}).catch(()=>{});return()=>{alive=false;};},[imagePaths,client]);
    const current=useRef(board),mounted=useRef(true),saving=useRef(false),viewport=useRef(null),gesture=useRef(null),selection=useRef(null),focusedCall=useRef(null),request=useRef(0),observed=useRef(false);
    current.current=board;const cam=camera[face];
    async function refresh(){const serial=++request.current;try{const value=unwrap(await client.board());if(mounted.current&&serial===request.current&&!saving.current){setBoard(value);if(!observed.current){observed.current=true;setNotice('');}}}catch(error){if(mounted.current)setNotice(error.message);}}
    useEffect(()=>{mounted.current=true;refresh();return()=>{mounted.current=false;request.current++;};},[client]);
    useEffect(()=>{if(!visible)return;refresh();const timer=setInterval(()=>{if(!saving.current&&!gesture.current)refresh();},2500);return()=>clearInterval(timer);},[visible,client]);
    useEffect(()=>subscribeBoardStream(sessionId,value=>{if(['completed','error'].includes(value.status)){setStream(null);refresh();setNotice(value.status==='error'?'这次板书未保存，保留上次保存的内容。':'');}else{setStream(value);setNotice('');}}),[sessionId,client]);
    async function save(target,patch,source=false){if(saving.current){setNotice('上一处调整正在保存，请稍后再试。');return;}saving.current=true;request.current++;setBusy(true);setNotice('');try{const result=unwrap(await client.mutateBoard({expectedRevision:current.current.revision,...(source?{sourcePath:target.path}:{blockId:target.id}),patch}));if(mounted.current)setBoard(result);}catch(error){if(mounted.current)setNotice(error.message);}finally{saving.current=false;if(mounted.current){setBusy(false);refresh();}}}
    async function saveInteraction(block,patch){if(saving.current){setNotice('上一处调整正在保存，请稍后再试。');return;}const ref=block.interactive;if(!ref)return;saving.current=true;request.current++;setBusy(true);setNotice('');try{const result=unwrap(await client.mutateBoardInteraction({boardRevision:current.current.revision,interactionId:ref.interactionId,interactionRevision:ref.revision,patch}));if(mounted.current){setBoard(result);setExpandedInteraction(previous=>previous?.id===block.id?result.blocks.find(item=>item.id===block.id)??null:previous);}}catch(error){if(mounted.current)setNotice(error.message);}finally{saving.current=false;if(mounted.current){setBusy(false);refresh();}}}
    const moveCamera=(patch,target=face)=>setCamera(prev=>({...prev,[target]:{...prev[target],...patch}}));
    const focus=(block,target=face)=>{const width=viewport.current?.clientWidth??500,z=Math.min(1,Math.max(.65,(width-48)/block.width));moveCamera({x:24-block.x*z,y:30-block.y*z,z},target);};
    let blocks=face==='board'?board.blocks:board.sources;
    if(face==='board'&&stream&&['streaming','pending'].includes(stream.status)&&stream.title){const existing=blocks.find(b=>b.title===stream.title);const preview={...(existing??{id:'pending-'+stream.callId,x:60+(blocks.length%3)*400,y:60+Math.floor(blocks.length/3)*320,width:340,kind:stream.kind??'note'}),title:stream.title,body:stream.body??existing?.body??'',stream:stream.status};blocks=existing?blocks.map(b=>b.id===existing.id?preview:b):[...blocks,preview];}
    useEffect(()=>{if(!follow||!stream?.title||focusedCall.current===stream.callId)return;const block=blocks.find(b=>b.title===stream.title);if(block){focusedCall.current=stream.callId;focus(block);}},[stream?.callId,stream?.title,follow,face]);
    const zoom=delta=>{setFollow(false);const rect=viewport.current.getBoundingClientRect(),z=Math.max(.3,Math.min(2,cam.z+delta));moveCamera({z,x:rect.width/2-(rect.width/2-cam.x)*z/cam.z,y:rect.height/2-(rect.height/2-cam.y)*z/cam.z});};
    const fit=()=>{setFollow(false);if(!blocks.length){moveCamera({x:0,y:0,z:1});return;}const rect=viewport.current.getBoundingClientRect(),els=[...viewport.current.querySelectorAll('.nb-block')];const left=Math.min(...blocks.map(b=>b.x)),top=Math.min(...blocks.map(b=>b.y)),right=Math.max(...blocks.map(b=>b.x+b.width)),bottom=Math.max(...blocks.map((b,i)=>b.y+(els[i]?.offsetHeight??260)));const z=Math.max(.3,Math.min(1,(rect.width-60)/(right-left),(rect.height-110)/(bottom-top)));moveCamera({z,x:(rect.width-(right-left)*z)/2-left*z,y:30-top*z});};
    const dragBlock=(event,block,source)=>{if(saving.current||block.stream)return;event.preventDefault();event.stopPropagation();setFollow(false);selection.current=null;gesture.current={type:'block',block,source,startX:event.clientX,startY:event.clientY,x:block.x,y:block.y};viewport.current.setPointerCapture(event.pointerId);};
    const pointerMove=event=>{const g=gesture.current;if(!g)return;const dx=event.clientX-g.startX,dy=event.clientY-g.startY;if(g.type==='pan')moveCamera({x:g.x+dx,y:g.y+dy});else{g.patch={x:Math.round(g.x+dx/cam.z),y:Math.round(g.y+dy/cam.z)};setBoard(prev=>({...prev,[g.source?'sources':'blocks']:prev[g.source?'sources':'blocks'].map(b=>(b.id??b.path)===(g.block.id??g.block.path)?{...b,...g.patch}:b)}));}};
    const endGesture=event=>{const g=gesture.current;gesture.current=null;if(viewport.current.hasPointerCapture(event.pointerId))viewport.current.releasePointerCapture(event.pointerId);if(g?.type==='block'&&g.patch)save(g.block,g.patch,g.source);};
    const selectText=(event,block,source)=>{const selected=window.getSelection();if(!selected||selected.isCollapsed||!event.currentTarget.contains(selected.anchorNode)||!event.currentTarget.contains(selected.focusNode))return;selection.current={block,source,text:selected.toString()};};
    const highlight=color=>{const selected=selection.current;if(!selected){setNotice('先选中板书或资料说明中的文字，再选择颜色。');return;}try{const body=highlightBoardText(selected.block.body,selected.text,color);save(selected.block,{body},selected.source);selection.current={...selected,block:{...selected.block,body}};}catch(error){setNotice(error.message);}};
    function download(type){const output=exportBoard(board,{...include,assetUrls,mathCss:document.querySelector('style[data-notara-math-styles]')?.textContent??''});const url=URL.createObjectURL(new Blob([type==='md'?output.markdown:output.html],{type:type==='md'?'text/markdown;charset=utf-8':'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='课堂笔记.'+type;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExporting(false);}
    const sourceMap=new Map(board.sources.map(s=>[s.path,s]));
    return h('div',{className:'nb-board'},h('style',null,css),
      h('header',{className:'nb-head'},h('div',{className:'nb-tabs',role:'tablist','aria-label':'白板两面'},[['board','课堂板书'],['sources','知识视图']].map(([id,label])=>h('button',{key:id,role:'tab','aria-selected':face===id,onClick:()=>{setFace(id);selection.current=null;}},label))),h('span',{className:'nb-status',role:'status'},busy?'正在保存…':stream&&['streaming','pending'].includes(stream.status)?'老师正在板书':board.revision?'已保存':''),h('button',{onClick:()=>setExporting(!exporting),'aria-expanded':exporting},'导出')),
      notice&&h('div',{className:'nb-notice',role:'status'},notice),
      h('div',{className:'nb-viewport',ref:viewport,'aria-label':face==='board'?'课堂板书画布':'本课资料关系画布',onPointerDown:event=>{if(event.target.closest('.nb-block,.nb-toolbar'))return;setFollow(false);gesture.current={type:'pan',startX:event.clientX,startY:event.clientY,x:cam.x,y:cam.y};event.currentTarget.setPointerCapture(event.pointerId);},onPointerMove:pointerMove,onPointerUp:endGesture,onPointerCancel:endGesture,onWheel:event=>{if(event.ctrlKey||event.metaKey){zoom(event.deltaY>0?-.05:.05);}else{setFollow(false);moveCamera({x:cam.x-event.deltaX,y:cam.y-event.deltaY});}}},
        h('div',{className:'nb-world',style:{transform:`translate(${cam.x}px,${cam.y}px) scale(${cam.z})`}},face==='sources'&&h('svg',{className:'nb-edges'},board.edges.map((edge,index)=>{const a=sourceMap.get(edge.from),b=sourceMap.get(edge.to);if(!a||!b)return null;const x=a.x+a.width,y=a.y+80;return h('g',{key:index},h('path',{d:`M ${x} ${y} C ${x+50} ${y},${b.x-50} ${b.y+80},${b.x} ${b.y+80}`}),h('text',{x:(x+b.x)/2,y:(y+b.y+80)/2-8},edge.label));})),blocks.map(block=>h(Block,{key:block.id??block.path,block,assetUrls,source:face==='sources',stream:block.stream,onDrag:dragBlock,onSelection:selectText,onSource:path=>openView(VIEW_IDS.assets,path),onInteractionChange:saveInteraction,onExpand:setExpandedInteraction,onDiscuss:text=>onDiscuss?.(text),onReturn:id=>{const target=board.blocks.find(b=>b.id===id);if(target){setFace('board');setFollow(false);focus(target,'board');}}}))),
      expandedInteraction&&expandedInteraction.interactiveScene&&h('div',{className:'nb-interactive-modal-host'},h(MathInteractive,{scene:expandedInteraction.interactiveScene,expanded:true,onChange:patch=>saveInteraction(expandedInteraction,patch),onDiscuss:text=>onDiscuss?.(text),onClose:()=>setExpandedInteraction(null)})),
        h('div',{className:'nb-toolbar',role:'toolbar','aria-label':'画布控制'},h('button',{'aria-label':'缩小',onClick:()=>zoom(-.1)},'−'),h('button',{'aria-label':'重置缩放',onClick:()=>moveCamera({z:1})},Math.round(cam.z*100)+'%'),h('button',{'aria-label':'放大',onClick:()=>zoom(.1)},'+'),h('button',{onClick:fit},'全览'),h('span',{className:'nb-sep'}),HIGHLIGHTS.map(color=>h('button',{key:color,className:'nb-color','data-color':color,'aria-label':colorNames[color]+'高亮',onMouseDown:e=>e.preventDefault(),onClick:()=>highlight(color)})),h('button',{'aria-label':'清除高亮',onMouseDown:e=>e.preventDefault(),onClick:()=>highlight(null)},'清除'),h('span',{className:'nb-sep'}),h('button',{className:'nb-follow','aria-pressed':follow,onClick:()=>{setFollow(!follow);focusedCall.current=null;}},follow?'跟随中':'跟随板书'))),
      exporting&&h('div',{className:'nb-export',role:'dialog','aria-label':'导出课堂笔记'},h('strong',null,'带走这一课'),h('div',null,'选择要包含的内容'),[['hint','已给出的提示'],['reference','参考推导'],['attempt','个人尝试']].map(([key,label])=>h('label',{key},h('input',{type:'checkbox',checked:!!include[key],onChange:e=>setInclude(prev=>({...prev,[key]:e.target.checked}))}),label)),h('div',{className:'nb-export-actions'},h('button',{onClick:()=>download('md')},'Markdown'),h('button',{onClick:()=>download('html')},'HTML'),h('button',{onClick:()=>setExporting(false)},'取消'))));
  };
}
